### ISSUE TITLE
Hiding columns

### ISSUE THREAD

**Issue by AviAkGlobal** [TonyGermaneri/canvas-datagrid#103]
### Expected behavior and actual behavior.
I've trying 'playing' with the width of columns in order to hide them, but as long as there's text the columns are being displayed. Is there a way to simply hide columns (and overriding all of the other stuff, such as text, cell width and so on)?

### Steps to reproduce the problem.
N/A

### Specifications like the version of the project, operating system, or hardware.
N/A

**Comment by TonyGermaneri** [comment]
Setting the [column's hidden property](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.header.hidden) to true hides the column.  

    var grid = canvasDatagrid({
        parentNode: parentNode,
        data: [
            {col1: 'foo', col2: 0, col3: 'a'},
            {col1: 'bar', col2: 1, col3: 'b'},
            {col1: 'baz', col2: 2, col3: 'c'}
        ]
    });
    grid.schema[1].hidden = true;

It seems like you should be able to set it to zero as well.  Did you try setting [minColumnWidth](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.style.minColumnWidth) as well?

**Comment by AviAkGlobal** [comment]
Actually, I've put 0.1... it doesn't work otherwise.
I've added an Array of hidden columns to the initialization of the grid. It accepts indexes to hide and during draw I'm setting the width of each cell as 0.1.
