### ISSUE TITLE
Retina screen optimization

### ISSUE THREAD

**Issue by michaelfich** [TonyGermaneri/canvas-datagrid#105]
### Expected behavior and actual behavior.

Expected: looks crisp on Macbook Retina screens.
Actual: Has a fuzzy look

### Steps to reproduce the problem.

If you view the demo, it looks somewhat blurry on the aforementioned screens.

### Specifications like the version of the project, operating system, or hardware.

See above.

I've found this article which may help in fixing the issue once reproduced locally:
https://coderwall.com/p/vmkk6a/how-to-make-the-canvas-not-look-like-crap-on-retina

**Comment by TonyGermaneri** [comment]
https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.args.maxPixelRatio

I'm aware of the problem, you can fix it with the `maxPixelRatio` setting.  The default setting of 1.5 "just a bit blurry".  Setting it to 2 will make it "nice and crisp" on a macbook retina.  It's a performance tradeoff.

I have a dozen or so ideas spinning in my head to improve performance, but I'm still working on major features so I'm holding off on any performance updates.  Once performance updates allow the grid to run > 30FPS at 1080p at the natural setting of 2 I'll set the default to 2.

**Comment by michaelfich** [comment]
Awesome!  Thanks so much for getting back to me so promptly.  I'll give that a try.

**Comment by michaelfich** [comment]
Changing it to a value of 2 as you suggested worked quite well for me.

**Comment by TonyGermaneri** [comment]
I've set the default to 2.  I don't think this issue will pop back up anytime soon, so I'm going to close it.
