### ISSUE TITLE
Text is blurry

### ISSUE THREAD

**Issue by cthurston** [TonyGermaneri/canvas-datagrid#109]
### Expected behavior and actual behavior.
Why is the text blurry?

### Specifications like the version of the project, operating system, or hardware.
Mac OS High Sierra: Safari and Chrome

**Comment by TonyGermaneri** [comment]
I'm aware of the problem.  Please see this link for instructions on how to fix it.

https://github.com/TonyGermaneri/canvas-datagrid/issues/105

**Comment by cthurston** [comment]
That looks perfect after setting the maxPixelRatio to >2.
