### ISSUE TITLE
Documentation project has bad overload code

### ISSUE THREAD

**Issue by TonyGermaneri** [TonyGermaneri/canvas-datagrid#110]
### Expected behavior and actual behavior.

isCellVisible appears twice in the docs with exact same documentation.   The overload code is ignored.

### Steps to reproduce the problem.

Make an overload entry.  E.g.:

        /**
         * Checks if a cell is currently visible.
         * @memberof canvasDatagrid
         * @name isCellVisible
         * @overload
         * @method
         * @returns {boolean} when true, the cell is visible, when false the cell is not currently drawn.
         * @param {number} columnIndex The column index of the cell to check.
         * @param {number} rowIndex The row index of the cell to check.
         */
        /**
         * Checks if a cell is currently visible.
         * @memberof canvasDatagrid
         * @name isCellVisible
         * @method
         * @returns {boolean} when true, the cell is visible, when false the cell is not currently drawn.
         * @param {cell} cell The cell to check for.  Alternatively you can pass an object { x: <x-pixel-value>, y: <y-pixel-value> }.
         */

**Comment by amjha** [comment]
Removing the second block of comment fixes this issue. I can have a PR with the change.

**Comment by TonyGermaneri** [comment]
Thanks!!!

**Comment by TonyGermaneri** [comment]
Thanks again for the PR @amjha!
