### ISSUE TITLE
last row is half or fully hidden for some heights.

### ISSUE THREAD

**Issue by sameeraroshan** [TonyGermaneri/canvas-datagrid#118]
when i put canvas data grid inside a re-sizable container and try to resize , last column disappear at some height values.

**Comment by TonyGermaneri** [comment]
Can you create an example?  Put the grid in a div, use a setTimeout to resize the div to the buggy state.

**Comment by sameeraroshan** [comment]
ill come up with an example tony.
meanwhile can you check at` dataHeight += columnHeaderCellHeight + columnHeaderCellBorder;` because i feel that you have missed the height of horizontal scroll bar.

**Comment by TonyGermaneri** [comment]
Quite possibly.  I've been trying to fix that slide scroll bug and breaking stuff while I'm doing it.  That's the last bug in the system that I'm not sure how to fix.  I'll be putting a lot of effort into this specific bug  this week.

**Comment by TonyGermaneri** [comment]
Any chance you have an example of this behavior?

**Comment by sameeraroshan** [comment]
Ill try to create one tony

**Comment by sameeraroshan** [comment]
you may close it tony. i did some tweaks to code at that time to solve it.
i didn't check with latest release. if i could reproduce it with
latest version , then ill let you know.

**Comment by TonyGermaneri** [comment]
Thanks @sameeraroshan, if you find the issue still persists please reopen it.
