### ISSUE TITLE
scrollIndexRect  scrollIndexBottom  scrollPixelBottom is wrong for last row is selected.

### ISSUE THREAD

**Issue by sameeraroshan** [TonyGermaneri/canvas-datagrid#119]
I've found the issue is in below code it doesnt go inside if statement to set values and scrollIndexRect returns the previous values.

### Issue
```
for (r = self.frozenRow + self.scrollIndexTop; r < l; r += 1) {
    n = self.orders.rows[r];
    if (!drawRow(n, r)) {
     self.scrollIndexBottom = r;
     self.scrollPixelBottom = y; 
        break;
    }
}
```

### Solution i added
```
for (r = self.frozenRow + self.scrollIndexTop; r < l; r += 1) {
    n = self.orders.rows[r];
    self.scrollIndexBottom = r; // moved outside form draw row
    self.scrollPixelBottom = y; // moved outside form draw row
    if (!drawRow(n, r)) {
        break;
    }
}
```

### Specifications like the version of the project, operating system, or hardware.
0.20.x

**Comment by TonyGermaneri** [comment]
Can you confirm this is behaving as expected now?

**Comment by sameeraroshan** [comment]
yes with the change i added , its working fine. you can go ahead with that.

**Comment by TonyGermaneri** [comment]
I added a fix that is very similar to the one you suggested.  I'll close the ticket after you confirm it is working.

**Comment by sameeraroshan** [comment]
I've tested and its working with "v0.20.11".
