### ISSUE TITLE
Column freezing not working

### ISSUE THREAD

**Issue by KrystianD** [TonyGermaneri/canvas-datagrid#121]
### Expected behavior and actual behavior.
Columns are moved to the right after freezing first column.
![image](https://user-images.githubusercontent.com/1083568/37868429-5a14273c-2fa6-11e8-91c5-9e90aaa6e230.png)

### Steps to reproduce the problem.
1. Go to https://tonygermaneri.github.io/canvas-datagrid/tutorials/demo.html
2. Drag column freeze marker to the right

### Specifications like the version of the project, operating system, or hardware.
Chromium | 65.0.3325.146 (Developer Build) (64-bit)
OS | Arch Linux

**Comment by TonyGermaneri** [comment]
Very sorry about that.  Major refactor in v0.20 caused a lot of bugs.  I'll get this fixed right up.

**Comment by KrystianD** [comment]
No issues! canvas-datagrid is great piece of software, you're doing very good job!

**Comment by TonyGermaneri** [comment]
This is in QA now.  Just to give you an update on the nature of the bug; it seems that hidden columns were being counted in the list of frozen columns.  Thanks for reporting the bug!!

**Comment by TonyGermaneri** [comment]
This issue still existed in some form, it's finally fixed.  It would occur again if there were many hidden columns and you tried to scroll.  The calculation on the visible scroll index changed incorrectly by not taking into account hidden columns before the frozen column.  Both the scroll and draw functions had to be updated.  It's nicer all around now.

**Comment by TonyGermaneri** [comment]
Well... there still appears to be some bugs around column freezing.  What remains is a strange bug that causes a "hiccup" in the horizontal scrolling when several columns are frozen.  Which is better than them disappearing, and that ain't bad.  So I have to leave the ticket open until I finally get it fixed completely.

**Comment by agileago** [comment]
@TonyGermaneri  Is there a way frozen column right? like `frozenColumn: [1]` , `frozenRightColumn: [2,3]` ?

**Comment by TonyGermaneri** [comment]
You can only freeze column on the left hand side.

https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.frozenColumn
