### ISSUE TITLE
Possibility to set data and format of specific cells after initialization

### ISSUE THREAD

**Issue by derblitz** [TonyGermaneri/canvas-datagrid#123]
Currently, it seems to me, the component cannot be manipulated incrementally (in terms of data and format).

Example: It should be possible (after grid initialization) to change the value in row 5 and column 10 from 'xxx' to 'yyy'.

Example 2: It should be possible (after grid initialization) to change the format of row 10 and column 2 from background yellow to background red.

**Comment by TonyGermaneri** [comment]
You can alter the data after initialization by altering the data, e.g.: `grid.data[5].a = 'yyy';` if your column was named `a`.  You can also use numbers as column names, but know you are refining an object, not a 2D array; e.g.: `grid.data[5][10] = 'yyy';`.  JS will coerce the number `10` into the string `'10'` in this case, but you can use what appears to be 2D array syntax, if you're not into the whole brevity thing.

You can [alter the text that appears in the cell on a per cell basis](https://tonygermaneri.github.io/canvas-datagrid/docs/#tutorial--Format-data-using-rendertext-event) by hooking into the `rendertext` event.  But it will work on a per cell basis and you can examine the content of the cell as well as the rest of the data or schema from that event.

You can also use the built in formatters to set the value of the data type by hooking into the [beforerendercell ](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:beforerendercell) event, I THINK, I've never done it before, I've always relied on rendertext, but it should work.

I hope this answers all your questions, if it does go ahead and close the ticket, if not, let me know how I can better clarify - or maybe I misunderstood the questions altogether.

**Comment by derblitz** [comment]
Ok. That makes it clear. Thank you!!!
