### ISSUE TITLE
Canvas-Data Grid Pivot Table

### ISSUE THREAD

**Issue by deepakchandra00** [TonyGermaneri/canvas-datagrid#124]
I need help - how to create a **pivot** table in Canvas-Datagrid. Kindly Help me.

**Comment by TonyGermaneri** [comment]
There is no pivot function built into the grid.  You can without much effort pivot the data on the grid or in the selection and map it to another part of the grid, recreate the grid, or into a new grid.

If you tell me where you'd like the data to go (new grid, another location in the grid, recreate the grid), I can write the function for you.

**Comment by deepakchandra00** [comment]
Thanks for your guidance....
This is what we're trying to do. the actual data is below:

              {id:"1",gender:"male",  eyes:"green", discount:"30",  sales:"1850"},
              {id:"2",gender:"male",  eyes:"brown", discount:"35",  sales:"10"},
              {id:"3",gender:"male",  eyes:"brown",  discount:"12", sales:"1800"},
              {id:"4",gender:"female",eyes:"brown",  discount:"17", sales:"500"},
              {id:"5",gender:"male",  eyes:"green",  discount:"19", sales:"100"},
              {id:"6",gender:"male",  eyes:"green", discount:"25",  sales:"3500"},
              {id:"7",gender:"female",eyes:"green",  discount:"64", sales:"180"},
              {id:"8",gender:"female",eyes:"brown", discount:"59",  sales:"9500"},
              {id:"9",gender:"male",  eyes:"brown", discount:"45",  sales:"5482"},
              {id:"10",gender:"male", eyes:"blue", discount:"21",    sales:"5684"},
              {id:"11",gender:"male", eyes:"blue", discount:"36",    sales:"214"},
              {id:"12",gender:"male", eyes:"black", discount:"18",   sales:"352"}

we're trying to get the data grid to display something like this in a new grid preferably:
           
       
![pivot](https://user-images.githubusercontent.com/11978365/39910668-e609995e-5515-11e8-892a-3cbdf64778a8.png)

**Comment by TonyGermaneri** [comment]
So sorry @deepakchandra00 I haven't been able to focus any time on this project in the last month, sorry for the delay.

The data in the grid is a array of objects or an array of arrays, manipulating the data is done the same way you would any standard JS data.

This looks like an elegant solution to the problem: https://medium.com/front-end-hacking/matrix-rotation-%EF%B8%8F-6550397f16ab

So what you'd do is:

`grid.data = flipMatrix(grid.data);` and maybe `grid.draw();`

If the grid is not disposing of the previous schema (the column names are not changing) you can tell it to always load a new schema when the setting data by setting the `autoGenerateSchema` property to true.

Sorry again for the delay and let me know if this helps.

**Comment by deepakchandra00** [comment]
thanks for your help
