### ISSUE TITLE
Integration with SheetJs and Angular 5

### ISSUE THREAD

**Issue by JuniorEC** [TonyGermaneri/canvas-datagrid#125]
### Expected behavior and actual behavior.

I'm using the data grid to display data from an exported worksheet using SheetJs, but when the data is passed to myGrid.Data, nothing is shown in the UI, however the <canvas-Datagrid> tag is created.
![capturar7](https://user-images.githubusercontent.com/24255719/39678606-2cc6f980-5166-11e8-930a-6ec175434f50.PNG)
![capturar8](https://user-images.githubusercontent.com/24255719/39678607-2cec0d88-5166-11e8-8dd9-099ab3c0780b.PNG)

### Steps to reproduce the problem.

**file.component.ts**
`var myGrid = canvasDatagrid({
  parentNode: document.getElementById('grid'),
  data: []
});`

**file.component.html**
`<div id="grid"></div>`

### Specifications like the version of the project, operating system, or hardware.
Angular 5
Windows 10
Opera browser @latest
Mozilla Firtefox @latest

**Comment by TonyGermaneri** [comment]
In your example, you have `data: []`.  That's where the data is supposed to go.  You can also add data using `myGrid.data = <yourdata>;`.  I hope this was the problem, please let me know if this works.

**Comment by JuniorEC** [comment]
This is my component, it gets an xlsx file, after that, it reads, and transforms into an Array<Array<any>>. I'm running this JSON-shaped Array for the datagrid.data.

`<h5>Drop files</h5>
			
<div class="container">
	<div class="row header-section">
		<div class="col-md-3">
			<div ng2FileDrop
				[ngClass]="{'nv-file-over': hasBaseDropZoneOver}"
				(fileOver)="fileOverBase($event)"
				[uploader]="uploader"
				(onFileDrop)="fileDropped($event)"
				class="well my-drop-zone">
				Jogue seu atquivo aqui
			</div>
		</div>
	</div>
</div>
<div id="grid"></div>
`

**And my component.ts**

`public doDataGrid(sheet: XLSX.WorkSheet) {
    var data = XLSX.utils.sheet_to_json(sheet, {header:1});
    console.log(data);
    
    var cDg;
    if(!cDg) cDg = canvasDatagrid({ parentNode:'grid', data:data });
    cDg.style.height = '100%';
    cDg.style.width = '100%';
    cDg.data = data;
    console.log(cDg);
    
    var range = XLSX.utils.decode_range(sheet['!href']);
    for(var i = range.s.c; i <= range.e.c; ++i) cDg.schema[i - range.s.c].title = XLSX.utils.encode_col(i);
  }
`
 @TonyGermaneri, Yesterday I tried to pass this:

`[
    {"col1": "row 1 column 1", "col2": "row 1 column 2", "col3": "row 1 column 3"},
    {"col1": "row 2 column 1", "col2": "row 2 column 2", "col3": "row 2 column 3"}
]`

 to the date[ ] and nothing happened as well.

**Comment by TonyGermaneri** [comment]
I was able to get it working in Firefox.  It seems I can't copy/paste from Firefox but I typed a bunch and it worked as expected.  Can you send me a code example where I can just copy and paste it to get the bug?  Maybe a JSFiddle?

I really don't like FF right now, it made me type quite a lot just now.

**Comment by JuniorEC** [comment]
I could not create the example = (
but the code is in the following links:

https://stackblitz.com/edit/angular-krppbs

https://github.com/JuniorEC/Excel-Visualization-And-Upload

**Comment by TonyGermaneri** [comment]
I see the problem here, that's a bug in the module loader I'm using, very sorry, I'll try and get it fixed.  I haven't been able to focus any time on this project in the last month, sorry for the delay.

**Comment by TonyGermaneri** [comment]
The bug occurs based on how you're loading the module.  It _probably_ reads from the package.json in which case it is pointed to raw source files.  I've updated the package.json to point to the distribution files.  I'll make another release and hopefully it will begin working.

**Comment by TonyGermaneri** [comment]
Please try v0.20.17.

**Comment by TonyGermaneri** [comment]
I think this is working, if it isn't please reopen the issue.
