### ISSUE TITLE
Question: is there any way to change value programmatic?

### ISSUE THREAD

**Issue by Imperat** [TonyGermaneri/canvas-datagrid#129]
I want allow users to open popup in which they can press button for setting some value of specific cell. There is any way to set it and refresh canvas immediately?

**Comment by TonyGermaneri** [comment]
Yes, you can set `grid.data[<row number].yourColumnName = <new value>;` .  If you want to redraw immediately you can call `grid.draw();`.

**Comment by Imperat** [comment]
Thank you for the answer.
I use your library in my project to develop killer-feature to my customer and they are so happy with it:)
