### ISSUE TITLE
Context menu - cursor pointer

### ISSUE THREAD

**Issue by Imperat** [TonyGermaneri/canvas-datagrid#130]
Hi, @TonyGermaneri.
Currently when I hover items on context menu my cursor looks like I want to edit text - "|". Can we implement cursor pointer for menu items? It can be more user-friendly as well :)

**Comment by TonyGermaneri** [comment]
I never noticed that!  For sure.

**Comment by TonyGermaneri** [comment]
v0.20.17 contains a new style called `contextMenuCursor`.  The default is `default` which is what I found the system context menu to be.  You can change it to pointer if you like pointer.  Thanks for noticing the issue!

**Comment by Imperat** [comment]
Thank you, @TonyGermaneri. I'll update version of your library in dependency list of my project!
