### ISSUE TITLE
Add ellipsis modes

### ISSUE THREAD

**Issue by TonyGermaneri** [TonyGermaneri/canvas-datagrid#132]
There should be at least 3 modes:

* `text`: Very slow.  Ellipsis is calculated using `measureText`.  Calculated text is stored in a cache that is invalidated on `resize`.  This provides the "perfect" ellipsis.

* `word`: Same as text, but clipped to the nearest word, much faster, should be the default.

* `gradient`: Slow.  Ellipsis is drawn onto the cell using a combination of gradient and text.  The gradient is drawn on top of the original value and ellipsis is drawn onto the gradient using the same font as the value text.

* `none`: Very fast.  Value is clipped by the edge of the cell.  There is no notification that text has been truncated in the UI.

**Comment by RayMckaig** [comment]
Could I suggest "Wrap" be a mode as well. Unless there is another way to wrap text in a cell.

**Comment by TonyGermaneri** [comment]
Right now the only way to wrap text is by using the innerHTML property, which is really crappy.  I'll add another issue to wrap text, it would be very useful.  Wrapping text implies justification as well, so that needs to be added.  Because canvas doesn't supply these text properties I have to make them up.  It does supply the height and width of the text, so it's straightforward, just a bit of work.

**Comment by TonyGermaneri** [comment]
> 1. When the parent container is resized the canvas scaling changes so the content shrinks or grows. Is there a way to maintain the 1:1 pixel relationships when first drawn.

This isn't supposed to happen, but it's hard to detect when the parent node has been resized, so it may be necessary to call `grid.resize()` when the grid's parent element has resized and the grid didn't detect it.  Currently I use mutation observers to watch all ancestor nodes, but it's not reliable.  Until the new W3C resize observer is implemented this will continue to be a problem. 

> 2. Some of our column headers are wordy hence the need to be able to wrap.

Yeah, I have a ticket to add text wrapping.  You can use `cell.innerHTML` property to pass HTML into the canvas and get the benefits of HTML/CSS.  It's a work around as the innerHTML property is kinda hackey.

> 3. Even setting header padding to zero and aligning column headers to the bottom there’s a 5-10 pixel gap between the text and bottom border.

There shouldn't be.  There are no numbers added "magically" to the calculations here.  If I understand you correctly, you're trying to make the text touch the border at the bottom of the header cell, correct?

> 4. When defining the schema, can you specify horizontal alignment?

No, schema is data layer, so it's not meant to have view related info (hidden not withstanding).  That said, you can indeed define it on your schema and then use a `grid.formatter` to later read the schema's information you added and alter the format (add alignment) of the cell as it is drawn onto the canvas.  If the docs aren't clear on how to do this, I can provide more examples.

> 5. How to you specify horizontal alignment when setting the data for a cell?

This sounds like question 4

> 6. The scroll bars seem a bit laggy, almost as if they’re on a timer. Is there a way to improve the responsiveness?

You can lower the resolution of the grid, or decrease the size of the grid.  It will improve with time as optimizations are applied, but I'm trying to keep optimizations undone until all features are complete.  

See: https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.args.maxPixelRatio

> 7. Is there a way to show checkboxes instead of row numbers to activate the highlighting of rows?

You can roll your own or you can wait until issue #128 is completed.  To roll your own you would attach a function to the `afterdraw` event and draw a checked, or unchecked checkbox onto the canvas using the object passed in the event's argument list `e.ctx`.  How you draw the two checkbox states is up to you.  I can provide examples of this if you need them.

**Comment by TonyGermaneri** [comment]
Wrap mode is now implemented via `grid.style.cellWhiteSpace = 'normal'`.  I also figured out a way to do the very fast per character ellipsis very fast and implemented it in #134.  You can "turn off" the ellipsis by setting `grid.attributes.ellipsisText = ''`, so I don't think the property `ellipsisMode` is useful anymore.
