### ISSUE TITLE
isColumnVisible and isRowVisible don't appear to work

### ISSUE THREAD

**Issue by rdavi10471a2** [TonyGermaneri/canvas-datagrid#138]
### Expected behavior and actual behavior.
console.log(grid.isColumnVisible(1)) should return whether or not the column is visible
trying to use this in the scroll event to tell what cols are actually in the viewport.
how can this be done

### Steps to reproduce the problem.
call this funciton
console.log(grid.isColumnVisible(1))

**Comment by TonyGermaneri** [comment]
Thanks for finding that bug.  It appears the functions are not exposed to the public interface.  It's easy to fix, I'll add it to the next release.

In the mean time...

This example shows the use of [scrollIndexRect](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.scrollIndexRect).  

https://tonygermaneri.github.io/canvas-datagrid/tutorials/xhrPagingDemo.html

https://github.com/TonyGermaneri/canvas-datagrid/blob/master/tutorials/xhrPagingDemo.js#L116

I think this should provide the information you're looking for.

**Comment by rdavi10471a2** [comment]
Awesome, thanks I will probably give it a try tonight and try to create a
fiddle of my attempt.
Let you know how it goes.
AWESOME work by the way.

RD
