### ISSUE TITLE
Add ability to insert input for edit cell in custom place of DOM

### ISSUE THREAD

**Issue by Imperat** [TonyGermaneri/canvas-datagrid#140]
I use canvas data grid with fullscreen api. When my div element (parent of canvas data grid) is going into fullscreen mode the input control is going to uneditable. 
Can we add api to insert input component in custom place of dom?

fiddle to reproduce bug with fullscreen mode:
http://jsfiddle.net/sg96jL3k/

**Comment by TonyGermaneri** [comment]
Thanks for the help!!  

I don't think this will break any previous implementations, but I could be wrong.

**Comment by Imperat** [comment]
Hi, @TonyGermaneri. Please, have a note that fullscreen mode also affects context menu. I'm going to fix it again in weekends

**Comment by TonyGermaneri** [comment]
Ah, yeah, it would.

**Comment by TonyGermaneri** [comment]
Hi @Imperat I've added the event appendeditinput to accommodate your use case.  Attach to the event and run `e.preventDefault();` to stop it from adding the input to the body.  You can then add the input where you like and alter it if need be.

**Comment by Imperat** [comment]
Thanks a lot, @TonyGermaneri. Now I use another event preventing for resolve this case. I forget it in today Sunday.. probably beforebeginedit :)
Tool which I implement using your library is actively used in production! Thank you again for you great library!

**Comment by TonyGermaneri** [comment]
> Tool which I implement using your library is actively used in production!

That makes my day!
