### ISSUE TITLE
Copy/Paste error in cell

### ISSUE THREAD

**Issue by NeoWorkPage** [TonyGermaneri/canvas-datagrid#146]
### Expected behavior and actual behavior.
expected: the correct behavior of data when paste data in cell
actual: when paste data into the cell, an error is displayed  `Cannot read property 'name' of undefined`

### Steps to reproduce the problem.
1) open link https://tonygermaneri.github.io/canvas-datagrid/tutorials/demo.html
2) copy data from cell
3) paste in cell
4) error `Cannot read property 'name' of undefined`

![-19-2018 12-15-55](https://user-images.githubusercontent.com/25130499/42933482-95f02fdc-8b4d-11e8-9dcb-917b437de971.gif)

### Specifications like the version of the project, operating system, or hardware.
MacOs High Sierra, Chrome 67.0.3396.99

**Comment by TonyGermaneri** [comment]
Thanks, looks like a bug that was introduced recently in 0.21.x.  I have no _proper_ automated tests for clipboard so it's fallen through the crack before.  I'll get it fixed.
