### ISSUE TITLE
Images cache critical issue

### ISSUE THREAD

**Issue by Imperat** [TonyGermaneri/canvas-datagrid#147]
Hello, @TonyGermaneri. Please, look at this jsfiddle:
http://jsfiddle.net/z47s0afg/

I render "test" string in second column of table via html.
Try to change height of first row.
Expected behavior: 
  all is perfect and life is good
Actual behavior: 
  browser will be crashed after 5-10 seconds.
I start discover this problem and it seems that this is the problem with images cache:
```
function drawHtml(cell) {
            var img,
                v = cell.innerHTML || cell.formattedValue,
                x = cell.x + self.canvasOffsetLeft,
                y = cell.y + self.canvasOffsetTop;
            if (self.htmlImageCache[v]) {
                img = self.htmlImageCache[v];
                if (img.height !== cell.height || img.width !== cell.width) {
                    // height and width of the cell has changed, invalidate cache
                    self.htmlImageCache[v] = undefined;
                } else {
                    if (!img.complete) {
                        return;
                    }
                    return self.ctx.drawImage(img, x, y);
                }
            }
```
We have two cells with same image, but with different size. Condition `(img.height !== cell.height || img.width !== cell.width)` returns true and it's revalidate cache in infinite cycle.

For ensure that this is really problem with cache revalidation I make this hack to cheat the cache:
http://jsfiddle.net/za5w24xv/
In second fiddle all works fine, but probably more slow (without using cache)

**Comment by TonyGermaneri** [comment]
It seems the size of the cell should be added to the `v` cache key name.  I'll get it fixed ASAP.

**Comment by TonyGermaneri** [comment]
v0.21.2 fixes this issue.  It seems that when using innerHTML it would go into a async never ending loop trying to redraw images that were already loaded and drawn.  I added a few more checks to make sure both cache does not conflict and the never ending loop does not occur.
