### ISSUE TITLE
unable to set widths of scrollbars individually

### ISSUE THREAD

**Issue by rdavi10471a2** [TonyGermaneri/canvas-datagrid#148]
### Expected behavior and actual behavior.
Can't find any way to individually set the height of the scrollbars independently.
setting the width property as you suggested does so for both scrollbars

possibly  adding additional public properties to override this logic?
 self.scrollBox.horizontalBarVisible = self.style.width !== 'auto' && dataWidth > self.scrollBox.width;            self.scrollBox.verticalBarVisible = self.style.height !== 'auto' && dataHeight > self.scrollBox.height;

### Steps to reproduce the problem.
try to set scrollbar width to 0

**Comment by TonyGermaneri** [comment]
It's easy enough to add the extra styles, I'll stick it in the next release.

**Comment by TonyGermaneri** [comment]
I didn't put it in the next release :( I am pond scum.  Next one for sure!

**Comment by rdavi10471a2** [comment]
understand believe me.
i know how it goes

**Comment by TonyGermaneri** [comment]
I've added overflow-x and overflow-y properties on the style object.  They behave as you might expect.  I'll have a release later today.

**Comment by TonyGermaneri** [comment]
If these overflow settings are not fixing your problem please reopen the ticket.

**Comment by rdavi10471a2** [comment]
doesn't seem to be working quite right
http://jsfiddle.net/qr1cythe/241/

I swear it has removed the horizontal scroll bar once or twice but re-rendering the screen brings it back.
Could be issues with the JS Fiddle site I don't know

**Comment by rdavi10471a2** [comment]
http://jsfiddle.net/cwevk79g/5/  example also does not work

**Comment by rdavi10471a2** [comment]
Order matters..whether it should or not is another question

  grid.style.overflowX = "hidden"
  grid.setColumnWidth(0, 60);
  grid.setColumnWidth(1, 200);
  grid.setColumnWidth(2, 200);
  grid.style.width = "316px";
  grid.style.height ="200px"

works


  grid.setColumnWidth(0, 60);
  grid.setColumnWidth(1, 200);
  grid.setColumnWidth(2, 200);
  grid.style.width = "316px";
  grid.style.height ="200px"
  grid.style.overflowX = "hidden"

does not
