### ISSUE TITLE
row header styles inconsistent unable to set row header width

### ISSUE THREAD

**Issue by rdavi10471a2** [TonyGermaneri/canvas-datagrid#150]
### Expected behavior and actual behavior.
     grid.style.rowHeaderCellWidth=5; 
    grid.style.rowHeaderCellSelectedBackgroundColor="yellow";
    grid.style.rowHeaderCellHoverBackgroundColor="cyan";
    grid.style.rowHeaderCellSelectedColor="pink"
    grid.style.rowHeaderCellColor= "black"
from
http://jsfiddle.net/qr1cythe/173/
selected and hover styles are not applied on the first row ( appears to be because it is already selected )
rowHeaderCellSelectedColor doesn't seem to work
rowHeaderCellColor doesn't seem to work
rowHeaderCellWidth has no effect but retrieves the value 57 if you query it.. so it is set but won't change the UI?

### Steps to reproduce the problem.
http://jsfiddle.net/qr1cythe/173/ has the code

### Specifications like the version of the project, operating system, or hardware.
document the effect of each of the row/column header styles so we know what to expect

**Comment by TonyGermaneri** [comment]
For the style question:

I think you need one more color property: [activeHeaderCellBackgroundColor](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.style.activeHeaderCellBackgroundColor) ?

Active cell is the cell the user has selected using the cursor keys or mouse (the first cell by default).  It also changes the color of the header row and column, so you might want to check all the active* values.  Selected colors override active colors.

Similar to this question: https://github.com/TonyGermaneri/canvas-datagrid/issues/82

For the header row width:

The style _does_ work but it is immediately overridden by the auto-size function that automatically sets the row header width depending on the width of the numbers in the column.  That way if you have sometimes large or sometimes small results the header rows will always be a sensible width.

> I figured, get to the part where I can change the damn width

So you can't turn off the auto-size-ing of the header row, and you probably don't want to dispose of all your user's custom sizing information, so just alter the sizing information using `grid.setColumnWidth(-1, <number>);`.  It may or may not be documented but -1 is the header row index.

Hope this answers your questions!

**Comment by rdavi10471a2** [comment]
Cool, I will give it a try.
is there a way to have something other than numbers in the row headers?

**Comment by TonyGermaneri** [comment]
Sure, add an event listener to `beforecellrender` event and alter the `formattedValue` of `e.cell`s where the `e.cell.columnIndex === -1`.  The formatted value is what will be displayed (falls back to normal value when formattedValue is `undefined`).  This way you can change the value at runtime for any cells, including the headers.

**Comment by rdavi10471a2** [comment]
lol I should have thought of the -1.. i knew that.. this is what happens
when you try to be creative with things after bed time
