### ISSUE TITLE
How to use canvas-datagrid  in Angular component

### ISSUE THREAD

**Issue by Navya-adft** [TonyGermaneri/canvas-datagrid#151]
First i install the canvas-datagrid ,after try to use <canvasdatagrid> tag ,but it gives error..

how to solve this problem ?

**Comment by Navya-adft** [comment]
now its worked

**Comment by TonyGermaneri** [comment]
Did you figure out what the problem was?  Was it related to the canvas-datagrid component?

**Comment by Navya-adft** [comment]
Not yet.
