### ISSUE TITLE
Questions on columnOrder API

### ISSUE THREAD

**Issue by LabShareLouie** [TonyGermaneri/canvas-datagrid#154]
Hi @TonyGermaneri,

Thanks for the quick feature release for columns sorting.

I've been playing around with it, and am able to retrieve the order using grid.columnOrder but cannot **set** the order. Looking over the docs, I assumed grid.columnOrder([1, 0 , 2, 3]) would work but got the error:

<code>grid.columnOrder is not a function</code>

May I get an example of how to set column order?

Thanks,
Louis

PS: Theres a duplicate entry for columnOrder in the API documentation https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.columnOrder

**Comment by TonyGermaneri** [comment]
All fixed!

https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.columnOrder

Thanks again for pointing this out.
