### ISSUE TITLE
Typescript typings?

### ISSUE THREAD

**Issue by domehead100** [TonyGermaneri/canvas-datagrid#155]
It would be nice to have Typescript typings for your component.  This helps with intellisense and also with the stricter type checking.  

I've created a file and could to a PR.  It would be just a matter of distributing the file along with your component in the root folder (where package.json exists).

I created the file partly by looking at the defaults for the params but mostly by writing a quick bit of javascript in the dev tools to pull stuff out of the API documentation page.  So, not everything is guaranteed to be correct, but it would be a good starting point.

There's also JSX setup, so you don't have to use React.createElement when using React.

**Comment by TonyGermaneri** [comment]
You are my new favorite person.

Let me show you this file:

https://github.com/TonyGermaneri/canvas-datagrid/blob/gh-pages/docs/js/reflection.js

It's the API-as-a-JS-object.  That's what I use to construct the API pages.  It is only created when you run `npm run build-docs`.  It exists in the documentation branch `gh-pages` only.  JSDOC creates the `reflection.js` file, you can use the same method to create your Typescript typing file.  You can write it in the same file or invoke another file from the npm build system.

If you want to do the JSX setup that would be really helpful too, or I can log it as a ticket and do it when time allows.

Let me know if I can do anything to help, I really love what you're doing.

**Comment by domehead100** [comment]
I took a look at the reflection.js file, and I've started working on a script to generate the typings from that.  Very neat.

When this is working, I'll have some questions on how to get it into the automated build, since it's in the gh-pages branch instead of master.

**Comment by domehead100** [comment]
Just an update.  I'm still going to do this (generate the typescript file from the JSDoc AST), just haven't had time to finish this up due to being busy with work, etc.  I'm actually attempting to use the grid in production code around importing and then manipulating spreadsheet data, so I'm getting some good real-world usage of the grid and the typings and the React binding, etc.

**Comment by josh-hemphill** [comment]
@TonyGermaneri & @ndrsn  would a conversion/partial rewrite of the project to typescript be something I could look into? 
In trying to create the multiple entries for controlling custom component, I'm running into all sorts issues with what internals are expected and when. Having the typings during development would make it a lot easier to make fundamental changes like this, and it would give me a good opportunity to get familiar with order of operation of everything. 
It would also mean TSC would handle the resolution of the one dependency, so bundlers wouldn't have to do anything with it for the various kinds of exports.

**Comment by ndrsn** [comment]
Yes! I would definitely be in favor of converting to TypeScript for obvious reasons, but I am skeptical of big-bang rewrites / conversions. (I have attempted a start, but abandoned it for lack of time)

Test coverage isn't great (yet; I'm looking into it), and I'm concerned large scale changes will inevitably introduce more bugs — in theory, converting to TypeScript should be a matter of merely adding type annotations everywhere. If you can do it like that (i.e. _just_ adding types), that would be amazing, but my gut feeling is that you'll end up running into issues which require moving code around and possibly unintentionally altering behavior. (It _is_ just a gut feeling of course, so I could be wrong)

So yes, I'm in favor, but only if it's done in incremental, controlled steps, which in my mind means _first_ adding a type definition file for the external (public) component interface, as discussed in this issue. This can then be tested as part of quality control (using something like [tsd](https://github.com/SamVerschueren/tsd)) to ensure nothing breaks. 

Then, you should be aware that the documentation now is generated using [JSDoc](https://jsdoc.app/) and the annotations in the files. As JSDoc does not handle TypeScript files (correct me if I'm wrong on this), and I'm not sure it makes sense to run `jsdoc` on the compiled files, we'll need to generate them in some other way. Perhaps [TSDoc](https://tsdoc.org/) is a solution?

Once we have type annotations for the external interface, _and_ there's a solution in place to generate documentation based on TS files, we're in a better place to convert all files to TypeScript files, and adding annotations everywhere else. The next logical step, I think, would be the non-public methods, and then whatever is left. Thoughts?

**Comment by josh-hemphill** [comment]
That all sounds really good.
Do you have any ideas about what would be a good way to track this? There's going to be a lot of steps involved.
I guess the first thing to do would be to add TSC to the build pipeline just to emit a ts definition.
TSDoc looks like it would be a good choice, it looks like it's actively being developed/pushed by microsoft, so tooling support should be pretty good. TSD looks good too, I've never thought about testing definitions, it makes a lot of sense even for some of my other projects.

**Comment by josh-hemphill** [comment]
I've been trying to get a .d.ts file created, but it's looking like I won't be able to use TSC, I don't know how JSDoc is getting all its type information, but TSC can only produce the very basic top-level attributes. 
e.g.
```ts
declare module "main" {
    export default function canvasDatagrid(args: any): HTMLElement | Grid;
    function Grid(args: any): {
        args: any;
    };
    namespace Grid {
        const observedAttributes: string[];
    }
    class Grid {
        constructor(args: any);
        disconnectedCallback: () => void;
        attributeChangedCallback: (attrName: any, oldVal: any, newVal: any) => void;
        connectedCallback: () => void;
        adoptedCallback: () => void;
    }
    export {};
}
```

**Comment by ndrsn** [comment]
> Do you have any ideas about what would be a good way to track this? There's going to be a lot of steps involved.

Good question! I don't _know_ exactly what each step should be, so know that I'm free-styling here: I think the first step is the one this issue (#155) has raised, namely: type annotations for the external interface.

Any steps beyond that should be new issues; the first of which, I'm thinking, would be configuring webpack/rollup to read the `.js` files as TypeScript files (possibly converting them to a `.ts` extension, but only when warranted). If that compiles and works (i.e. the output passes the tests, it can be used), without changing anything in the source (i.e. no new type annotations just yet), I think we'd be ready to slowly add types. But then you'll probably run into the documentation generation, so we'd need some hybrid Frankenstein documentation generator, using whatever JSDoc/.js files we have left, along with the new TypeScript files.

> I've been trying to get a .d.ts file created, but it's looking like I won't be able to use TSC, I don't know how JSDoc is getting all its type information, but TSC can only produce the very basic top-level attributes.

Yeah, I don't think we're going to get a lot out of attempting to automatically infer types — just yet, at least. So the first step will probably have to be done manually, or using the existing JSDoc type annotations: `jsdoc` uses the JSDoc annotations in the source files to generate `reflection.js`, which can be used to generate a type file. [See the above comment](https://github.com/TonyGermaneri/canvas-datagrid/issues/155#issuecomment-412200915).

**Comment by josh-hemphill** [comment]
Yeah, I was thinking we could get the "Projects" enabled for the repo and track the issues there in case we have multiple going at once and in case anyone else wants to know where we are in the process.

Personally I was thinking of just leaving the JS alone and creating the TS in another directory to keep it all organized. That way we can keep the docs and build settings the same until its side-by-side TS code has been thoroughly tested/vetted and can provide the same or similar docs. That way it works more like a migration and we can always provide or remove any bundles we need to without impacting those that need maximum backwards compatibility; at least until TS is ready and can be released under a breaking change semver version to be safe.

When I get some time I'm going to try using [microsoft's dts-gen](https://github.com/microsoft/dts-gen) to get inferred types, I'm thinking it might at least get similar results to JSDoc.

Side note: I don't think it really needs a separate issue yet, but while messing with .d.ts generation I realized that the whole `window.canvasDatagrid` assignment is sort of an anti-pattern since both webpack and rollup are capable of building IIFE bundles; at some point (probably after TS) I'd like to look at replacing the global assignment with an IIFE bundle output.

**Comment by ndrsn** [comment]
> Yeah, I was thinking we could get the "Projects" enabled for the repo and track the issues there in case we have multiple going at once and in case anyone else wants to know where we are in the process.

I don't feel like the administrative weight has gotten to a point where we need project boards to keep track of things.

> Personally I was thinking of just leaving the JS alone and creating the TS in another directory to keep it all organized.

You _could_ do it that way, of course, but I stand by my earlier comment regarding 'big-bang' rewrites or migrations: it tends to be pretty risky to attempt to switch everything over all at once instead of gradually. Perhaps I don't understand what you're proposing, but another reason for small, incremental steps is not only reducing risk, but giving reviewers (us) manageable chunks to review and provide feedback on, whereas a very large pull request is nobody's idea of a good time.

**Comment by TonyGermaneri** [comment]
There's a pattern in architecture called the "strangler pattern" that would have us proxy all API calls via a method router.  At first 100% of the calls would be directed to the legacy API, as the new modules are built out and take over, the router would redirect calls to the new module.

This allows us to not have to "boil the ocean".  Complete rewrites typically result in an undesirable outcome.

That said, there are some automated tools that might be worth looking at.  There's likely a lot of `any` types that will be injected in this method.  Still might be something that can instantly port the whole thing programmatically: https://github.com/airbnb/ts-migrate/tree/master/packages/ts-migrate

**Comment by josh-hemphill** [comment]
I finally figured out the first part! 🤯 There's tsd-jsdoc. 
Typescript won't guess at types, and the dts-gen library is incredible, but broken and currently dead.
That took way longer than it should have.

**Comment by josh-hemphill** [comment]
Wow, after all that, I just realized the jsdoc type information is all in the `lib/docs.js`.

**Comment by TonyGermaneri** [comment]
It's not all of it.  It is scattered across all the source files.  The stuff in lib/docs.js is just the stuff that didn't seem right sticking into other files.  Almost 100% of the methods and properties should have definitions on them.

This process extracts all the type data and sticks it into a JS file during the doc build process.

https://github.com/TonyGermaneri/canvas-datagrid/blob/8c95617aae5921eab0f72c65943891e8aa2e6831/tutorials/publish.js#L25

This is the file it produces: https://github.com/TonyGermaneri/canvas-datagrid/blob/gh-pages/js/reflection.js

That file is build along with the documentation on each deploy via the CI/CD pipeline.  If you want to use that pipeline to publish a type doc right after I think that seems like the right spot.

**Comment by josh-hemphill** [comment]
Yeah. Though it contains the main object interface that is probably the most important, and doesn't seem to get picked up by the TS compiler. I was really scratching my head how jsdoc was magically getting all that information; I just totally missed the file right in front of me. :joy:

**Comment by Dassderdie** [comment]
According to the changelog for `0.3.0` the typings should already be there, but I can't find any `.ts`-file when installing `canvas-datagrid@0.3.1` or downloading the zip from https://github.com/TonyGermaneri/canvas-datagrid/releases/tag/v0.3.1 ...

**Comment by ndrsn** [comment]
Ah, whoops, this should not have been closed! Apologies.

Yeah, I noticed that too, sorry about that. Not sure what's going on, but I believe it's the GitHub workflow that's not correctly set up. I've verified that `npm run build:types` correctly generates the file in `dist/`, but for some reason the file isn't being published to NPM or included in the zip file. I'll have to look into this Friday or this weekend.

**Comment by ndrsn** [comment]
Further, based on a cursory glance I've also noticed the typings are not in all cases correct when it comes to return types. Most are listed with a return type `void` when they in reality return a boolean or something else.

**Comment by ndrsn** [comment]
@Dassderdie, the 0.3.2 version should include typings now, but since they're based on fallible JSDoc annotations, as my previous comment indicates we cannot vouch for them being fully correct or entirely useful — but it's a start. Hopefully this will get us on a path to righteousness.

Many thanks to @josh-hemphill for doing the work on this.
