### ISSUE TITLE
selectionchanged event fires on mouse move and doesn't fire at all if selectionMode is set to "row"

### ISSUE THREAD

**Issue by domehead100** [TonyGermaneri/canvas-datagrid#158]
### Expected behavior and actual behavior.
I would expect the "selectionchanged" event to only fire when the user selects rows with the mouse (by clicking or clicking and dragging a rubber band selection rectangle) or the keyboard by holding Ctrl or Shift keys and moving to additional cells.  Instead, it seems to fire every time the mouse hovers over a cell.  I also don't think that it fires reliably (or maybe not at all) if I click on the row header cell to select an entire row that way when not in "row" selectionMode.

When the selectionMode is set to "row", I'd expect the selectionChanged event to fire when the user clicks on a row, but instead it never fires at all in "row" selectionMode as far as I can tell.

### Steps to reproduce the problem.
Add an event listener for the "selectionchanged" event and see that it triggers basically every time you move the mouse.  

Set the selectionMode to "row" and see that the handler for "selectionchanged" never fires, even if you click on a row or rows.

### Specifications like the version of the project, operating system, or hardware.
Latest version, Windows 10

**Comment by TonyGermaneri** [comment]
It should only fire when the selection changes, this sounds like a bug.  The event should fire when rows are selected as well.

**Comment by domehead100** [comment]
Well, it seems to work correctly in, for example, http://jsfiddle.net/xz9tvbr8/1/.  So, maybe there's something I'm doing that's stupid.  I'll try to track this down.

It does not trigger the selectionchanged event when a row is selected, however.

**Comment by TonyGermaneri** [comment]
Still a bug then, good to know it's not completely broken.

This is the universal method that everything uses for setting individual row selection [`selectRow`](https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/publicMethods.js#L455).

The embarrassingly complex [`mouseMove`](https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/events.js#L417) function that invokes the `selectRow`... and it looks to me like it has been set to not fire the event for some reason that is unbeknownst to me.  `self.selectRow(o.rowIndex, ctrl, null, true);`  (the function signature is: `self.selectRow = function (rowIndex, ctrl, shift, supressEvent)`) ... so looks that that's the bug, just have to set that `true` to `false` and make sure it doesn't break everything.  

I really can't think of a reason why it's set to `true` (`supressEvent`), nothing internally uses the event system.  The only reason I have `supressEvent` is to make sure things like `selectAll` don't cause `eventListener * row.length` functions to fire off, which seems like undesirable behavior for the person listening to the `selectionchanged` event, a select all should produce 1 event.  There are other places too, like holding the shift key and selecting a range or using they keyboard to select a range with shift.  All of these loop through many rows running `selectRow` and then manually firing the `selectionchanged` event after the loop.

Feel free to pick up this issue.  Seems very easy to fix.  Just gota make sure tests still pass.

**Comment by asolas** [comment]
selectionchanged not fired when "columnHeaderClickBehavior"  set to "select" too
