### ISSUE TITLE
Cells not editable in IE11

### ISSUE THREAD

**Issue by decatur** [TonyGermaneri/canvas-datagrid#162]
### Expected behavior and actual behavior.
Cells should be editable. Under IE11, no input field is shown, and the cell cannot be edited.

### Steps to reproduce the problem.
With IE11, open https://tonygermaneri.github.io/canvas-datagrid/tutorials/demo.html and dblclick any cell.

### Specifications like the version of the project, operating system, or hardware.
IE 11.0.9600.19080

### Workaround
Do not append input to canvas element (it is not a valid sub-element of canvas imho), but to its parent node:
    self.parentDOMNode.parentNode.appendChild(self.input);

**Comment by TonyGermaneri** [comment]
This isn't surprising.  There were some modifications made to the input 2-3 versions back that caused some breaking.

> Do not append input to canvas element (it is not a valid sub-element of canvas imho), but to its parent node:

The value of  `self.parentDOMNode` is captured during instantiation and isn't a canvas.  It is either the parent of the canvas or the shadow dom depending on browser capabilities.  I _used_ to be `body` or shadow dom put to a few versions ago.  The problem had to do with the canvas being put into full screen mode, it would occlude any elements not in the full screen element causing the input to not be seen.

So there needs to be implemented a way for each use case to work.  It shouldn't be too hard, I think worse case is I'll add a new event listener that allows for the user to select which element the input gets attached.  As a work around you can try pulling an earlier version of the grid or fork it and fix it for your specific use case, if it works for full screen as well as your case make a PR and I'll merge it into master.

Thanks for the help!

**Comment by TonyGermaneri** [comment]
Through some strange arrangement of feature detection it was indeed being shoved into the canvas element as you suggested, I never witnessed it myself until yesterday.  I've added the event `appendeditinput` to handle the different use cases.  Your use case should just work now, people trying to use edit on full screen or other unconventional ways will have to attach to the event handler to get it to append to the element that works best for them.
