### ISSUE TITLE
All columns are not displayed in the screen

### ISSUE THREAD

**Issue by Navya-adft** [TonyGermaneri/canvas-datagrid#166]
when i use canvas-datagrid to display the excel file ,it only display 7 columns in the screen ,other columns are missed. the row length is works fine

**Comment by TonyGermaneri** [comment]
By default, the grid expands to fit the size of the content that is passed to it, you can constrain the content by passing a height and/or width value.  It sounds to me like you need to adjust the width of the canvas-datagrid element.  Can you provide any code or what browser you're using?

**Comment by Navya-adft** [comment]
i only use 	
`              var cdg = canvasDatagrid();
		document.getElementById('grid').appendChild(cdg);
		document.getElementById('grid').style.width = "100%";
		document.getElementById('grid').style.height = "100%";`

not use any other styles for the grid. and i tested in chrome ,mozilla and Edge ,all have the same problem

**Comment by TonyGermaneri** [comment]
You should treat the `cdg` var as any other dom element.  I believe you're modifying another element with the id `grid` which I assume is a `div` that is holding the grid, then you're modifying that div.  Trying modifying the `cdg` element instead. e.g.:

```
var cdg = canvasDatagrid();
document.getElementById('grid').appendChild(cdg);
cdg.style.width = "100%";
cdg.style.height = "100%";
```

Please reopen this issue if your problem isn't resolved.

**Comment by Navya-adft** [comment]
Still i have the problem
