### ISSUE TITLE
Bug selecting row/cells after calling columnOrder w/ hidden columns in schema

### ISSUE THREAD

**Issue by LabShareLouie** [TonyGermaneri/canvas-datagrid#172]
Hi Tony,

Playing around with the columnOrder function, I seem to have found a bug. If functions are called in this order: grid.data > grid.schema (w/ columns hidden) > grid.columnOrder, clicking on a x-axis header will not select a full row. Instead selecting one cell. This in turn messes with copy and pasting of selected data into spreadsheets.

Attached is test code of the producible bug where:
- Clicking on an x-axis header does not select a full row
- Cannot copy and paste all selected data if an area is highlighted by Ctrl+C/P into a spreadsheet

It seems to have something to do with calling the columnOrder function. Hope this helps! 

Regards,
Louie

[test.txt](https://github.com/TonyGermaneri/canvas-datagrid/files/2483565/test.txt)

**Comment by TonyGermaneri** [comment]
Thanks Louie,  I'll get it fixed.  Was an error thrown or was the behavior just wrong?

**Comment by LabShareLouie** [comment]
@TonyGermaneri I didn't see an error thrown, so it seems like just the behavior.

**Comment by TonyGermaneri** [comment]
Thanks so much for the sample code, that helped a lot in tracking down the issue.  I seems it would occur even if the user reordered the columns.  All fixed up now.
