### ISSUE TITLE
Table not drawing full on data amount over ~650

### ISSUE THREAD

**Issue by coorum** [TonyGermaneri/canvas-datagrid#174]
### Problem is
Noticed that if the data amount is over ~650, the table is cutting on this number, but the sizes of table are good (inline styles saying that)

**Comment by TonyGermaneri** [comment]
Do you have an example?  The max on my computer (late 2017 macbook i7) 75m rows with 10 columns.  This seems to have to do with a browser memory limit, not the lib.

**Comment by coorum** [comment]
Providing image proof
![image](https://user-images.githubusercontent.com/32096016/47492638-22f3f300-d856-11e8-9d33-6dd787244faa.png)

My data is 1000 rows with 7 columns for now

And here is the code that I'm using

    var grid = canvasDatagrid();    
    grid.data = data;
    grid.addEventListener("endedit", function (e) {
      console.log(grid.data); // or grid.changes to show only changes
    });

    grid.addEventListener("contextmenu", function (e) {
      e.items.push({
        title: "Delete this column",
        click: function (ev) {
          var _columnIndex = grid.currentCell.columnIndex;

          grid.deleteColumn(_columnIndex);
        }
      });
    });

    _showData.addEventListener("click", function () {
      console.log(grid.data);
    });

**Comment by coorum** [comment]
Tried the same on different machines, but the result is still the same

**Comment by coorum** [comment]
Solved this problem with setting css of grid through JS

**Comment by TonyGermaneri** [comment]
I see, yeah, I should surface that info in the manual a little better.
