### ISSUE TITLE
How to get the remain's data after I removed some columns?

### ISSUE THREAD

**Issue by huangchuxian** [TonyGermaneri/canvas-datagrid#177]
When I remove some columns, I want to get the data ignore the columns I have removed.
I see the API Dos, there is a Parameter, but I don't know how to use :

> 

Name | Type | Optional | Default | Description
-- | -- | -- | -- | --
args.columnSelectorVisibleText | string | ✔ | '    ' | When a column is hidden, this is the value to the left of the title in the column selector content menu.

eg:

### All Data:
![image](https://user-images.githubusercontent.com/9958489/47641289-a9833a00-dba0-11e8-8f1d-13aeeec56777.png)
![image](https://user-images.githubusercontent.com/9958489/47641358-cfa8da00-dba0-11e8-9034-5a504b8656c5.png)
### Remove column A:
![image](https://user-images.githubusercontent.com/9958489/47641441-054dc300-dba1-11e8-9145-74f0303baf69.png)
![image](https://user-images.githubusercontent.com/9958489/47641455-14347580-dba1-11e8-9d75-088f128df0d1.png)
_Column A is still here. I want get the data but not include column A._

**Comment by coorum** [comment]
Are you removing or just hiding this column?

**Comment by huangchuxian** [comment]
Thanks! But if I just hiding this column, how can I get the column I have hided, or get the column I haven't hided?

**Comment by huangchuxian** [comment]
> Are you removing or just hiding this column?
> I've created an extra option in context menu to delete the column, this way will remove it from data
> 
> ```
>   grid.addEventListener("contextmenu", function (e) {
>      e.items.push({
>      title: "Delete this column",
>      click: function (ev) {
>         var _columnIndex = grid.currentCell.columnIndex;
> 
>         grid.deleteColumn(_columnIndex);
>         console.log("Updated data", grid.data);
>       }
>     });
>   });
> ```

Thanks! But if I just hiding this column, how can I get the column I have hided, or get the column I haven't hided?

**Comment by TonyGermaneri** [comment]
Hiding columns does not remove the column from your data.  Hiding is to remove it from the _view_ of the user.  By default the user can hide/unhide columns using the context menu.  `args.columnSelectorVisibleText` sets the value of the "checked/unchecked" HTML, it has nothing to do with the appearance of the data.

What you want to do is [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) the data prior to using it.  So for example if I wanted to remove the column called b:

```
var outputData = grid.data.map(function (row) {
    var outputRow = {};
    Object.keys(row).forEach(function (colName) {
        if (colName === 'b') { return; }
        outputRow[colName] = row[colName];
    });
    return outputRow;
});
```

`outputData` will be without the column `b` after the map.  This has nothing to do with the grid lib, just plain old JS.
