### ISSUE TITLE
iOS Safari/Chrome compatibility?

### ISSUE THREAD

**Issue by coorum** [TonyGermaneri/canvas-datagrid#178]
### The Problem
After setting data source for table on iOS device (iPhone SE, iOS 12.0.1 + iPhone 7, iOS 12) the table is not drawing, unfortunately there is no option to debug webpage 
### Working Devices
Android Virtual Device (Android 9.0)
Pixel 2 XL (Android 9.0)

**Comment by TonyGermaneri** [comment]
Although it runs like shit I am able to open the demo up on my ipad/safari.  Do you have any code to look at?  Maybe I can spot the problem or worse case hook up a debugger to my ipad.

**Comment by coorum** [comment]
**UPD:** Found a way to debug iOS Safari on Windows and the console doesn't show any errors, everything there like on desktop or Android devices

Yep, here is the code that I'm using now

     function drawGrid(data) {
        console.log("XLSX Successfully Imported");
        $("canvas-datagrid").remove();
        var grid = canvasDatagrid({
                showPerfomance: true
            }),
            _showData = document.getElementById("close");

        $(".wrapper").append(grid);

        grid.style.height = '100%';
        grid.style.width = '100%';

        grid.data = data;

        grid.addEventListener("endedit", function (e) {
            console.log(grid.data); // or grid.changes to show only changes
        });

        grid.addEventListener("contextmenu", function (e) {
            console.log(e.cell);
            var _columnIndex = e.cell.columnIndex,
                _rowIndex = e.cell.rowIndex;

            e.items.push({
                title: "Delete this column",
                click: function (ev) {
                    grid.deleteColumn(_columnIndex);
                }
            }, {
                title: "Delete this row",
                click: function (ev) {
                    grid.deleteRow(_rowIndex);
                }
            });
        });

        _showData.addEventListener("click", function () {
            console.log(grid.data);
        });
    }

**Comment by TonyGermaneri** [comment]
try swapping 

```
    grid.style.height = '100%';
    grid.style.width = '100%';

    grid.data = data;
```

to

```
    grid.data = data;

    grid.style.height = '100%';
    grid.style.width = '100%';
```

There are some undesirable behaviors I'm struggling with around data setting and height/width.  The data setter sets the height and width of the grid if isn't otherwise specified, and sometimes it's really not clear if it has been specified (from the point of view of the lib), and it can change from browser to browser (in 2018!).  Swapping data setting and height/width settings can help.  It looks like everything else is legit.  By V1 I'll have the performance issues on IOS and android fixed, still working on features.

**Comment by coorum** [comment]
Thank you @TonyGermaneri, that's worked

**Comment by coorum** [comment]
@TonyGermaneri My email - coorum.y@gmail.com

**Comment by TonyGermaneri** [comment]
I sent out an invite.  Hope to see you there!
