### ISSUE TITLE
contextmenu append to

### ISSUE THREAD

**Issue by coorum** [TonyGermaneri/canvas-datagrid#180]
After e.preventDefault() and appending changes to context menu, I want to append it to DOM, but I can't find what exactly I need to append (neither items nor ctx are not working), who can help me?

**Comment by TonyGermaneri** [comment]
Your question isn't clear.  What are you trying to append to DOM?  The context menu?  What exactly isn't working?

**Comment by TonyGermaneri** [comment]
I re-read what you posted, I think you're having difficulty getting things to actually appear in the context menu.  This is from the demo page: https://github.com/TonyGermaneri/canvas-datagrid/blob/master/tutorials/demo.js#L105

It shows how the demo page added items to the context menu.  I hope this help.
