### ISSUE TITLE
Bug selecting row/cells after calling columnOrder w/ hidden columns in schema Pt. II

### ISSUE THREAD

**Issue by LabShareLouie** [TonyGermaneri/canvas-datagrid#181]
Hi @TonyGermaneri,

Issue [#172](https://github.com/TonyGermaneri/canvas-datagrid/issues/172) does not seem to be fully patched. After updating to 0.22.3, I reran the script
[test.txt](https://github.com/TonyGermaneri/canvas-datagrid/files/2548644/test.txt) with the updated version, however the copy and pasting function is still selecting blank/wrong columns.

Screenshot of bug attached. 

<img width="944" alt="screen shot 2018-11-05 at 8 48 58 am" src="https://user-images.githubusercontent.com/34035322/48002298-2484ad00-e0d9-11e8-858d-5d0c13ba1fb6.png">

As you can see Column 3 (Test 3), Column 6 (Test 6), and Column 1 (Test 1) are copied, but Column 5,  Column 6, and Column 4 are pasted. Column 5 and Column 4 are also blank.

Sincerely, 
Louie

**Comment by LabShareLouie** [comment]
PS: Also copying just one cell will paste a blank into excel too.

@TonyGermaneri Although I am being very nit-picky with your product, I really value it! Thank you for making it, I am sure the fussy bugs will be fixed in time :)

**Comment by TonyGermaneri** [comment]
Thanks for the update.  I probably hosed one of the mime types when I was fixing plain text.  That's certainly nothing like your selection.  I'll make sure I test it in excel before I declare it fixed again.

Thanks

**Comment by TonyGermaneri** [comment]
This hopefully is the final fix for this bug. https://www.youtube.com/watch?v=aNaXdLWt17A  I tested it using plain text and Google Sheets:
1) reordering with hiding
2) reordering without hiding
3) not reordering with hiding
4) not reordering without hiding

I know there are some oddities around jagged selections, there's a breaking change that needs to happen to fix the poor jagged copy precision.  I'll open another ticket for that once I make a demo of the bug, but it's pretty rare.

**Comment by LabShareLouie** [comment]
Thanks and happy new years!
