### ISSUE TITLE
Hi, how can i add two buttons in every row

### ISSUE THREAD

**Issue by Hybueno09** [TonyGermaneri/canvas-datagrid#182]
### Expected behavior and actual behavior.
I want to add two buttons in every row.
Click the button,one is to delete data of selected row, the other one is to change data.
The docs said i can draw HTML via Event,but it maybe very very slow.

So is there any other better proposal to solve my problem, thx much.

**Comment by Hybueno09** [comment]
It's a large single-page table.
Can i draw the button before render data? If i can, then how and which is the best way...

**Comment by TonyGermaneri** [comment]
The guy in #82 posted some example code on how to draw an image into a cell. 

You can draw the button first and save the image buffer in memory, then stamp it onto the canvas when you need it.  That'll speed up drawing considerably.  Sounds neat, I'm not 100% sure how to do it.

You'll still have to handle the click too.
