### ISSUE TITLE
Is it possible to group-by columns value?

### ISSUE THREAD

**Issue by shankscript** [TonyGermaneri/canvas-datagrid#191]
### Expected behavior and actual behavior.
<img width="876" alt="screen shot 2019-01-22 at 12 18 30 am" src="https://user-images.githubusercontent.com/2862389/51493502-89e46200-1ddb-11e9-9e42-c503784f3230.png">

Is it possible to create groupings by column's value as shown above? Where same values of one column (ex: materials is repeated in many rows which is now grouped followed by multi level drill downs for multiple columns)

**Comment by TonyGermaneri** [comment]
I don't think this is possible without a lot of hacky event listener work.  What you would end up with is a collection of grids that you would not be able to contiguously select across without a lot more hacky event listener work.

That said, it does appear to be possible.  Start by adding tree grids into tree grids, then set the column resize event listener on all of them to resize all the related grid columns so they stay uniform.  Then when a tree grid opens, make sure to set the height of the inner tree grid to the maximum possible.

After that, you'll need to intercept any selection events and re apply them across the multiple grids (each "drill in" is a new grid, drawn offset onto the same canvas and bound to the parent grid's events).

Let me know if you decided to go down this harrowing path, I'm happy to help you along the way.

Cheers!
