### ISSUE TITLE
Automatic calculation of column sizes from content

### ISSUE THREAD

**Issue by AuHau** [TonyGermaneri/canvas-datagrid#192]
It would be very cool if the data grid could calculate the size of columns based on the passed data. It would help with displaying more column-intense grids.

I guess there would also have to be a setting for min/max size.

**Comment by AuHau** [comment]
I just noticed that it supports the Excel's feature of "auto resize on double click on column's edge". Is there then a way how to enforce this on load of data?

**Comment by TonyGermaneri** [comment]
Yes, you can!

This does it on load:
https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.args.autoResizeColumns

This does it on demand:
https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.fitColumnToValues

Cheers!

**Comment by AuHau** [comment]
Oh damn, I was going through the docs for this option, but I guess missed it.

Thanks a lot for the info!
