### ISSUE TITLE
Problems with afterRenderCell

### ISSUE THREAD

**Issue by AdamPacanowski** [TonyGermaneri/canvas-datagrid#194]
### Expected behavior and actual behavior.
Expected behavior: 
When you define afterRenderCell event and assign some HTML grid will render it propertly. 

Actual behavior:
1. IE11 doesn't render anything. (In example only affected cells aren't rendered.)
2. On Chrome and Firefox you can see glitch.
![image](https://user-images.githubusercontent.com/1764149/51794447-dbbe2b00-21d3-11e9-8c10-d46ceb65fc50.png)
After grid rerender everything is ok, but initial state is wrong.

You can observe it on your example.
1. Open "Draw HTML via Event". 
2. Look on second column (shadow).
3. Force rerender (e.g. move cursor above grid)
4. Shadow has decreased.

### Steps to reproduce the problem.
Run https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#tutorial--Draw-HTML-via-Event 
and https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#tutorial--Draw-HTML-via-data-type
on IE11

### Specifications like the version of the project, operating system, or hardware.
Latest version (0.22.9).
Windows 10

**Comment by TonyGermaneri** [comment]
The render via html uses a SVG sub document.  This sub document does not implement 100% of the HTML5 spec, so experimentation is required.  If you need absolute accuracy you should use a canvas drawing function, which is complex to implement.  Otherwise do the best you can with the sub-document capabilities.

You can also try using the inbuilt styling functions to alter the appearance of the cells.  If all you want to do is change the font or colors this results in a nicer appearance.

I'm not sure why it wouldn't work in IE11.  I'll have to get in a VM an debug it.  Does it log any errors in IE11?

**Comment by AdamPacanowski** [comment]
Thank you for your response. 

Yes, IE11 throws an exception.
![image](https://user-images.githubusercontent.com/1764149/52164944-f0318480-26f9-11e9-86b5-2adade9cb5d7.png)
Exception translation: "Unexpected method call or access to property"

**Comment by TonyGermaneri** [comment]
Thanks @AdamPacanowski I found this on the net.

https://stackoverflow.com/questions/25214395/unexpected-call-to-method-or-property-access-while-drawing-svg-image-onto-canvas

Looks to be a bug in IE with a workaround that should work for this project as well.

The draw function needs to be wrapped in a setTimeout.  I would try a requestAnimationFrame first.  Easy fix either way.  I won't be able to get around to it for a few days, but I'm happy to merge a PR in the meantime.

`return self.ctx.drawImage(img, x, y)`

should be changed to
```
requestAnimationFrame(function () {
    self.ctx.drawImage(img, x, y);
});
return;
```

According to the article that should fix it.  I don't think it'll really matter for other browsers if it's doing the extra frame, if it's a nuisance I can add the browser detection in later.

Thanks for the report @AdamPacanowski I hope to get it fixed soon.

-Tony

**Comment by ndrsn** [comment]
I'm closing this issue, as we've dropped support for IE11.
