### ISSUE TITLE
Formatters called unnecessarily?

### ISSUE THREAD

**Issue by rowanhill** [TonyGermaneri/canvas-datagrid#197]
### Expected behaviour and actual behaviour.
More of a question than a bug report, but I'll follow the bug report format.

I've noticed that formatters for cells get called a lot more than I'd expect. For example, the formatter for every cell seems to get called every time the mouse moves. I would expect them only to be called when a cell needs to redraw, and I would expect that to only happen when data changes / when there's some user interaction.

### Steps to reproduce the problem.
- Supply a schema where cells have a type
- Provide data for the schema
- Add grid.formatters.yourtype = yourFormatterFunction; (perhaps with a console.log in yourFormatterFunction so you can easily see how often it's called)

### Specifications like the version of the project, operating system, or hardware.
I'm using version 0.22.9 from npm, with a small React wrapper around it (based off the React example given here). I'm testing on Chrome 71 on Windows 10.

**Comment by TonyGermaneri** [comment]
That is to be expected.  The grid redraws every mouse move to draw cell hover effects if any.

Of course this can be optimized quite a lot, but it isn't (for now).  If you find repeat calls to your formatter functions are causing a slowdown can I suggest you use memoization/memoization+debouncing?  It should lessen the load on your formatter functions to be within a tolerable volume.

Even with further optimization the formatter functions would get called quite a lot.
