### ISSUE TITLE
error in example vueExample.html

### ISSUE THREAD

**Issue by strange97** [TonyGermaneri/canvas-datagrid#198]
### Expected behavior and actual behavior.

Hi,
in Firefox and Edge the datagrid didn't appear and firefox give this error:  `NotSupportedError: Operation is not supported`

### Steps to reproduce the problem.

Open link https://tonygermaneri.github.io/canvas-datagrid/tutorials/vueExample.html with Firefox or Edge
NOTE: using Crome/Opera is working fine

### Specifications like the version of the project, operating system, or hardware.

Firefox 65, 66b3 on Windows 10
Microsoft Edge 44.17763.1.0

**Comment by kasbah** [comment]
I see the same error in the React and Web Components example. All other examples seem to work fine. Also on Firefox 65.

**Comment by TonyGermaneri** [comment]
This same error was pointed out in safari.  It seems to have to do with the order in which I'm applying properties to the web component.  I will try and get it fixed ASAP.
