### ISSUE TITLE
scrollTop on smaller grids

### ISSUE THREAD

**Issue by cthurston** [TonyGermaneri/canvas-datagrid#202]
### Expected behavior and actual behavior.
Expect the scrollTop to not be reset on smaller grids when clicking or adjusting the window.

### Steps to reproduce the problem.
Create a grid with 20 rows.  Set the height of the screen to be greater than 50% of the height of the resulting grid.  Meaning that you can scroll between 10 and 20.  If the scroll is less than 50% of the height the bug will not show up.  For example, if 5 rows of the 20 are visible the bug will not occur.  If 14 rows of the 20 are visible the bug will occur.  

Scroll down to row 4 and click of adjust the window size a little.   The scroll will jump back to the top.

### Possible causes/fixes:
If I comment out the guards in the setters that reset the scrollTop back to 0 it seems to fix it, but I'm not sure what the ramifications are for that.  The values of scrollHeight seem really strange.

```js
Object.defineProperty(self.scrollBox, 'height', {
                get: function () {
                    return sHeight;
                },
                set: function (value) {
                   //  if (scrollHeight < value) {
                   //      scrollTop = 0;
                   //  }
                    sHeight = value;
                }
            });
```
```js
Object.defineProperty(self.scrollBox, 'scrollHeight', {
                get: function () {
                    return scrollHeight;
                },
                set: function (value) {
                    if (scrollTop > value) {
                        scrollTop = Math.max(value, 0);
                    }
                    // if (scrollHeight < sHeight) {
                    //   scrollTop = 0;
                    // }
                    scrollHeight = value;
                }
            });
```

Any insight on what scrollHeight is?  And what these guards are doing?

**Comment by TonyGermaneri** [comment]
Looks like a mistake on my part.  I think it should be removed. 

I read it like 20 times now, I don't know what it's doing.   Ok, I looked at the whole scroll module and I still don't know what those three lines are doing in there.  Looking through the history, it's been there for more than 2 years so the bug has probably been a around for a while and maybe even cascaded into other bugs.

Based on the typical reasons that I would set scrollTop to 0 in a abstracted module like that would be, as you rightly pointed out, as a sanity check on the input from the implementer.  But this isn't a sane sanity check.

It says: "if the height of the scroll box is less than the height of the grid, then set the scroll top to be 0 (scroll to the top)" which makes absolutely no sense.  I'm sure I meant well, and probably _thought_ I had a valid use case here, but I don't see it now.

Thanks for finding it.  You can open a PR or I'll fix it later.
