### ISSUE TITLE
Protecting a range of cells (making them uneditable)

### ISSUE THREAD

**Issue by anthonychung14** [TonyGermaneri/canvas-datagrid#204]
I'm exploring whether or not to try a canvas-based approach, but part of our requirements is to configure the table so that only a range of columns are editable.

Is it possible with this library without stitching together multiple canvas instances?

**Comment by TonyGermaneri** [comment]
Yes, you can attach to the [beforebeginedit](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:beforebeginedit) event and call `e.preventDefault();` when `e.cell.columnIndex` or `e.cell.header.name` are within the range you wish to make read only.

    grid.addEventListener("beforebeginedit", function (e) {
        if (e.cell.columnIndex > 2 && e.cell.columnIndex < 5) {
            e.preventDefault();
        }
    });

I didn't actually run this code.
