### ISSUE TITLE
Get TypeError: undefined is not an object (evaluating 'e.data.length')

### ISSUE THREAD

**Issue by ghost** [TonyGermaneri/canvas-datagrid#207]
Hi,
I've checked out version 0.12.12 by npm. In Vue I instantiate an empty table by this code:

```
mounted() { 
	this.grid = document.createElement('canvas-datagrid') 
	this.grid.style = { cellBackgroundColor: 'white', cellColor: 'black' } 	this.grid.schema = this.schema 
	for(let key in this.args) { 
		this.grid.attributes[key] = this.args[key] 
	} 
	this.$el.appendChild(this.grid) 
}, 
```

This is leading to an undefined error in publicMethods.js line 347:

bottom: self.data.length - 1

I suppose just to check self.data before using it, because it's set from outside.
What about a throw statement to inform user that attached data are invalid?

Regards
Andreas

**Comment by TonyGermaneri** [comment]
this is the function where the problem is occuring

        self.selectAll = function (dontDraw) {
            self.selectArea({
                top: 0,
                left: -1,
                right: self.getSchema().length - 1,
                bottom: self.data.length - 1
            });
            if (dontDraw) { return; }
            self.draw();
        };

I can't imagine how that is getting called based on the code you've pasted there.  It wouldn't be terrible to check if `self.data` has a value before checking the length property.

        self.selectAll = function (dontDraw) {
            if (!self.data || !self.data.length) {
                return;
            }
            self.selectArea({
                top: 0,
                left: -1,
                right: self.getSchema().length - 1,
                bottom: self.data.length - 1
            });
            if (dontDraw) { return; }
            self.draw();
        };

Should fix the problem.  I'll drop a fix in there in a day or two.

**Comment by ndrsn** [comment]
As we're now referencing `viewData` instead of `data`, and `viewData` is explicitly being set upon initialization, this issue should no longer be relevant, and can therefore be closed 🎉
