### ISSUE TITLE
null value ignored

### ISSUE THREAD

**Issue by vanillamasonry** [TonyGermaneri/canvas-datagrid#212]
### Expected behavior and actual behavior.
data
[[null,null,c,null,null,d]]
expected
A | B | C | D | E
   |     | c  |    | e 

actual
| C | E
| c | e 

### Steps to reproduce the problem.
content=btoa(',,c,,e')
WorkBook=XLSX.utils.book_new();
WorkBook=XLSX.read(content,{type:"base64"});
grid.data=XLSX.utils.sheet_to_json(WorkBook.Sheets[WorkBook.SheetNames[0]], {header:1});

**Comment by vanillamasonry** [comment]
Sparse data will imply strange results

**Comment by TonyGermaneri** [comment]
Auto detection of the schema data (number and name of columns) is based on the first row of data.

If you don't want to have your data auto detected you can specify a schema prior to (or simultaneously during instantiation) setting your data.  In the case of spreadsheet data you should just write a function that makes a large enough schema to fit your data onto.  If you expect your data to expand you can always change the schema at runtime, adding to it as your data grows.

    grid.schema = [
        {name: "A"},
        {name: "B"},
        {name: "C"},
        {name: "D"},
        {name: "E"},
    ];

That ensures that even if there is no data you get the columns you're expecting.

I hope that solves your problem.

Cheers
