### ISSUE TITLE
invalid input field

### ISSUE THREAD

**Issue by RaymondLi1101** [TonyGermaneri/canvas-datagrid#213]
### Expected behavior and actual behavior.
It is not a actual big issue cause the function works well. But every time I create a data grid. There will be a extra input field popping up on the page. It is read only and with style.

### Steps to reproduce the problem.
I tried both JS and web component to create data grid. Same issue happens. Can't locate this input field.

**Comment by TonyGermaneri** [comment]
That's normal.

https://tonygermaneri.github.io/canvas-datagrid/docs/#supporting-dom-elements
```
Although the grid itself is pure canvas, there are some supporting elements of the grid that are HTMLElements.

In order to overlap parts of the page that are not on the canvas, the context menu is a <div>.
In order to support advanced key commands, copying, pasting as well as user customization outside of this library, the editing input/textarea is DOM.
A hidden input is placed outside of the visible area of the web page to capture keystroke and translate them into grid commands, such as cursor navigation.
```

I think the element you're noticing is the last element.  Is there something wrong with it?  You say it's invalid.  Do I need to do something to make it valid?  Or are you just surprised to see it at all?  Some elements cannot receive key commands, so I use this input field to pick up key commands while you're focused on the grid (arrows, page up/down, copy/paste, etc.).

Hope this answers the question.

**Comment by RaymondLi1101** [comment]
Thank you. That's not a big issue. It just conflicts with my own page a little but it is a easy fix. Thank you for answering.
