### ISSUE TITLE
how can i add anchor tag in every row

### ISSUE THREAD

**Issue by AbhayLodhi** [TonyGermaneri/canvas-datagrid#214]
Hi, I need to add anchor tag in url columns of my data grid (so when user click on given url he will redirect to that link )

`var grid = canvasDatagrid({
    parentNode: parentNode,
    data: [
        {col1: 'foo', col2: "https://www.google.com/", col3: 'a'},
        {col1: 'bar', col2: "https://www.google.com/", col3: 'b'},
        {col1: 'baz', col2:"https://www.google.com/", col3: 'c'}
    ]
});
grid.addEventListener('afterrendercell', function (e) {
    if (e.cell.columnIndex === 1 && e.cell.rowIndex > -1) {
        e.cell.innerHTML = '<a target="_blank" href="https://www.google.com/">'
            + e.cell.value
            + '</a>';
    }
});
grid.draw();`

I try to modify this example give in docs. but it was not work for me.plz help

**Comment by TonyGermaneri** [comment]
When using HTML in the canvas it is only a picture of the HTML, it is not interactive.

To do what you want to do, just attach a click handler to the cell that navigates when it is clicked on.

`grid.addEventListener('click', function (e) { window.location = e.cell.value; });`

(I didn't run that, it might have errors)

**Comment by AbhayLodhi** [comment]
> When using HTML in the canvas it is only a picture of the HTML, it is not interactive.
> 
> To do what you want to do, just attach a click handler to the cell that navigates when it is clicked on.
> 
> `grid.addEventListener('click', function (e) { window.location = e.cell.value; });`
> 
> (I didn't run that, it might have errors)


Thank you so much @TonyGermaneri its work grt.
here is my code.
`this.grid.addEventListener('click', e => {
            if (e.cell.columnIndex === 7 && e.cell.rowIndex > -1 && e.cell.value != null) {

                window.open(e.cell.value, '_blank')
            }

        })
        this.grid.addEventListener('rendercell', e => {
            if (e.cell.columnIndex === 7 && e.cell.rowIndex > -1 && e.cell.value !=null) {
                e.ctx.fillStyle = '#AEEDCF'
            }
        })`

**Comment by AbhayLodhi** [comment]
I want to ask some more thing plz.

1) how can i chane the text color of url column.

2) It is possible to make funnel icon in header same like tringal icon avaliable for sorting. In my case user also want a funnel icon in table header. so when he click on funnel icon filter box will open  same as one avaliable when we do right click on header.  

Thank you.

**Comment by TonyGermaneri** [comment]
> how can i change the text color of url column.

I believe the property is called "cellColor"

You can see an interactive full list of styles here:
https://tonygermaneri.github.io/canvas-datagrid/tutorials/styleBuilder.html

If you want to change all of them, you can use:

     grid.style.cellColor = 'dodgerblue';

If you want to do it per cell you can use:

    grid.addEventListener('rendertext', function (e) {
        if (e.cell.header.name === 'Ei' && /omittam/.test(e.cell.value)) {
            e.ctx.fillStyle = '#AEEDCF';
        }
    });

https://tonygermaneri.github.io/canvas-datagrid/docs/#tutorial--Conditionally-set-colors

In this example, it is testing if the cell value contains "omittam" in the column "Ei" and setting the color to #AEEDCF.  You have the right idea, just the wrong event for the text color, the tutorial only describes the background unfortunately.  There are plans to make this easier, but this is how you do it for now.

Cheers,
Tony

**Comment by TonyGermaneri** [comment]
I just discovered the documentation lacks the information for your second question.

There is an undocumented attribute `filterTextPrefix` that will allow you to set the value of the "(filtered)" text.  You could replace this with other text or a glyph.

e.g.:

    grid.style.filterTextPrefix = "^";

The other option is to use `filterTextPrefix` to turn off the text by passing it an empty string, then draw your own image/vector/whatever in the headers of filtered columns during the `rendertext` or `afterrendercell` events.

**Comment by AbhayLodhi** [comment]
> > how can i change the text color of url column.
> 
> I believe the property is called "cellColor"
> 
> You can see an interactive full list of styles here:
> https://tonygermaneri.github.io/canvas-datagrid/tutorials/styleBuilder.html
> 
> If you want to change all of them, you can use:
> 
> ```
>  grid.style.cellColor = 'dodgerblue';
> ```
> 
> If you want to do it per cell you can use:
> 
> ```
> grid.addEventListener('rendertext', function (e) {
>     if (e.cell.header.name === 'Ei' && /omittam/.test(e.cell.value)) {
>         e.ctx.fillStyle = '#AEEDCF';
>     }
> });
> ```
> 
> https://tonygermaneri.github.io/canvas-datagrid/docs/#tutorial--Conditionally-set-colors
> 
> In this example, it is testing if the cell value contains "omittam" in the column "Ei" and setting the color to #AEEDCF. You have the right idea, just the wrong event for the text color, the tutorial only describes the background unfortunately. There are plans to make this easier, but this is how you do it for now.
> 
> Cheers,
> Tony

It means i can't change the condition based font colors for now.

Thank you Sir @TonyGermaneri

**Comment by TonyGermaneri** [comment]
If I understand you correctly, it sounds like you think you _can't_ change the text color.  But you can.

Maybe it wasn't super clear.  You can change the text color conditionally.  Notice the changed event name here:

    grid.addEventListener('rendertext', function (e) {}

It's `rendertext` vs `rendercell`.  That will change just the text color and not the background.

Cheers,
Tony

**Comment by AbhayLodhi** [comment]
> I just discovered the documentation lacks the information for your second question.
> 
> There is an undocumented attribute `filterTextPrefix` that will allow you to set the value of the "(filtered)" text. You could replace this with other text or a glyph.
> 
> e.g.:
> 
> ```
> grid.style.filterTextPrefix = "^";
> ```
> 
> The other option is to use `filterTextPrefix` to turn off the text by passing it an empty string, then draw your own image/vector/whatever in the headers of filtered columns during the `rendertext` or `afterrendercell` events.
------------------------------------------------------------------------------------------------------------------
Sir  I try to make somthing like this. when user click on funnel icon then filter field appers 

![applicationserver (3)](https://user-images.githubusercontent.com/9107412/58239861-82bc6900-7d67-11e9-855d-eb3a53dc18dc.png)

**Comment by TonyGermaneri** [comment]
An icon is more difficult than text.  I would first try selecting a font that has a filter icon glyph in it and then use that character for `grid.style.filterTextPrefix`.

If you need to use a graphic, you need to hook into the `rendercell` event and use the e.ctx (canvas 2d context reference) to draw a picture on the cell.  You can use e.cell.x, e.cell.y, e.cell.height, and e.cell.width to determine where the picture needs to go, but is enough code where I don't have the time right now to type it out.  You can look up "how to draw images on canvas" and use `e.ctx` and the x, y, height, width, to position the icon.

Also, use e.cell.rowIndex, and e.cell.columnIndex to determine what row and column you are on.  You don't want to draw the icon in every cell.

Reacting to the click is a little bit easier, but the same thing.  Add a `click` event, and detect the cell the user clicks on with e.cell.rowIndex and e.cell.columnIndex.  Then detect where exactly the user has clicked with e.NativeEvent.clientX, and e.NativeEvent.clientY and do the offset math to calculate where in the cell they have clicked.

You might want to check the `e` object, there might be some click position information in there that could save you some time, I can't recall.

Hope that helps, sorry I haven't the time to write the code.

Cheers,
Tony

**Comment by AbhayLodhi** [comment]
> An icon is more difficult than text. I would first try selecting a font that has a filter icon glyph in it and then use that character for `grid.style.filterTextPrefix`.
> 
> If you need to use a graphic, you need to hook into the `rendercell` event and use the e.ctx (canvas 2d context reference) to draw a picture on the cell. You can use e.cell.x, e.cell.y, e.cell.height, and e.cell.width to determine where the picture needs to go, but is enough code where I don't have the time right now to type it out. You can look up "how to draw images on canvas" and use `e.ctx` and the x, y, height, width, to position the icon.
> 
> Also, use e.cell.rowIndex, and e.cell.columnIndex to determine what row and column you are on. You don't want to draw the icon in every cell.
> 
> Reacting to the click is a little bit easier, but the same thing. Add a `click` event, and detect the cell the user clicks on with e.cell.rowIndex and e.cell.columnIndex. Then detect where exactly the user has clicked with e.NativeEvent.clientX, and e.NativeEvent.clientY and do the offset math to calculate where in the cell they have clicked.
> 
> You might want to check the `e` object, there might be some click position information in there that could save you some time, I can't recall.
> 
> Hope that helps, sorry I haven't the time to write the code.
> 
> Cheers,
> Tony

Thank you Sir @TonyGermaneri  I will try to do same as you said.

**Comment by AbhayLodhi** [comment]
Thank you Sir @TonyGermaneri I will try to do same as you said.
