### ISSUE TITLE
Copy is not title first

### ISSUE THREAD

**Issue by gjchentw** [TonyGermaneri/canvas-datagrid#216]
### Expected behavior and actual behavior.
When schema is offered with name and title, copy on all data of datagrid to clipboard still use name instead of title as header row, which may be done by
[event.js:1260](https://github.com/TonyGermaneri/canvas-datagrid/blob/71217ae00f26cadbbfa884bc94617435762d24d3/lib/events.js#L1260)

### Steps to reproduce the problem.
1. With this [jsfiddle](https://jsfiddle.net/gjchen/put7x61y/4/), given schema and data:
```
var parent = document.getElementById("data");
var schema = [
  { name: 'col1', title: 'Title 1'},
  { name: 'col2', title: 'Title 2'},
  { name: 'col3', title: 'Title 3'}
];
var data = [
  {col1: 'row 1 column 1', col2: 'row 1 column 2', col3: 'row 1 column 3'},
  {col1: 'row 2 column 1', col2: 'row 2 column 2', col3: 'row 2 column 3'}
];
var grid = canvasDatagrid({parentNode: parent, schema: schema, data: data});
```

2. Copy all the data of the grid, paste to a plain text editor will get the result:

```
/*
copied result:

"col1","col2","col3",
"row 1 column 1","row 1 column 2","row 1 column 3"
"row 2 column 1","row 2 column 2","row 2 column 3"
*/
```

### Specifications like the version of the project, operating system, or hardware.

canvas-datagrid: 0.22.12
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36

**Comment by TonyGermaneri** [comment]
That was done by design.  There are two options.  You can hook into the [copy event](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:copy) and change the data before it reaches the clipboard.  Or we can add a new parameter (would require code changes to the lib) that says something like "useSchemaTitleForCopy"... that's a terrible name, but you get the idea.

Let me know how you would like to proceed.

Cheers,
Tony

**Comment by gjchentw** [comment]
Considering schema is given by users, how about add a function **copyAs**, just like **sorter**, to [canvasDatagrid.header](https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.header), witch default is

```
copyAs: function() {
  return (this.name || this.title) || '';
}
```

Then, the **hVal** of [events.js:1260](https://github.com/TonyGermaneri/canvas-datagrid/blob/71217ae00f26cadbbfa884bc94617435762d24d3/lib/events.js#L1260) could use the **copyAs** function to get copied text:

```
var hVal = column.copyAs()  || '';
```

So that users can just rewrite **copyAs** to customize copied text  each schema of column.

Regards,

**Comment by TonyGermaneri** [comment]
I'm ok with that.  Did you consider using an event pattern?  Maybe a new event like `cellcopyvalue`.  I think event interfaces are a little to read.  Or both?  I can see how the schema concept is more "config" like and would work better for programs like Vue, but it also seems a little less flexible.  Maybe I'm just biased.  I like both though.  Do you want to make a PR?

**Comment by gjchentw** [comment]
How about dispatching event in function `addHeader`, says `copyOnSchema`, to hook to let people changing the result that addHeader does. It has less configs Andy more flexibility.

I would like making a PR, can I have a quick link to Code of Conduct or something?

**Comment by TonyGermaneri** [comment]
That sounds good.  Make sure you use native event class as your event object and keep the event name all lower case per the W3C specifications for web components.
Cheers

**Comment by gjchentw** [comment]
sure, it goes to `copyonschema`

Cheers
