### ISSUE TITLE
Question: is there any way to copy table to clipboard programmatically?

### ISSUE THREAD

**Issue by anastasi-a** [TonyGermaneri/canvas-datagrid#218]
Is there any way to copy table to clipboard programmatically by pressing the button, without manually selecting and using ctrl/cmd + C?

**Comment by TonyGermaneri** [comment]
Clipboard interaction falls into a security scope for the browser manufactures, so the behavior has changed a bit over time.  Right now, I think it might be possible if the event is chained properly to a user event, but considerable experimentation is required to determine the correct event->code path for every browser.

https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event

Ideally you could bind a click event to a button, then run the execCommand method and bind the grid data to the clipboard.  There used to be a context menu item for copy, then it stopped working so I've disabled it by default.  I'd love to have it working again.

I hope you can get it working based on that info.

Cheers,
Tony

**Comment by Imperat** [comment]
Hi, @anastasi-a 
You can use Clipboard API and put text into it:

```
navigator.clipboard.writeText(text);
```

Your `text` variable must represent state of your table in one string. In my project I used next way to convert table into string: I join each cell in row with `\t` symbol, and join each line with `\n` symbol:

```
  arrayToText: array => array.map(row => row.join('\t')).join('\n')
```

Please, be sure that your grant permissions to work with Clipboard API and your users have latest versions of modern browsers

**Comment by anastasi-a** [comment]
@TonyGermaneri, @Imperat Thank you for your responses.
event.clipboardData.setData('text/plain', selection.toString()) isn't very useful for me because I need copy data in a table format.
So I solved the problem by this way:
`  this.dataGrid.focus();
    this.dataGrid.selectAll(true);
    document.execCommand('copy');
    this.dataGrid.selectNone(true);`
