### ISSUE TITLE
Sorting rows not working

### ISSUE THREAD

**Issue by anastasi-a** [TonyGermaneri/canvas-datagrid#222]
### Expected behavior
Sort rows by clicking on column headers.

### Actual behavior
Doesn't sort rows if sorting column data has number type.

**Comment by TonyGermaneri** [comment]
You need to specify in your schema data that the column is a data type number.  If no schema is provided the grid assumes all data is string data.

**Comment by anastasi-a** [comment]
@TonyGermaneri  Thank you! It works!
