### ISSUE TITLE
Styling headers

### ISSUE THREAD

**Issue by anastasi-a** [TonyGermaneri/canvas-datagrid#223]
Is there any way to style row and column header in bold? 

Because now we have opportunity to change font size and font family, but not font weight:

columnHeaderCellFont: '12px sans-serif'
rowHeaderCellFont: '12px sans-serif'

**Comment by TonyGermaneri** [comment]
Sure, but it's unconventional compared to HTML/CSS.  With there is a ticket to improve this behavior, but for now, you need to use a event handler to hook into the drawing of the data, then alter the canvas context.  Usually you just need to change a few parameters, then the grid will draw the specified data using the style you set in the event handler.

These two links will help you with what you're trying to do.

https://tonygermaneri.github.io/canvas-datagrid/docs/#tutorial--Conditionally-set-colors

https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_text

Cheers
