### ISSUE TITLE
Adding arrow to column header

### ISSUE THREAD

**Issue by anastasi-a** [TonyGermaneri/canvas-datagrid#232]
Is it possible to style column header cell by adding arrow like it's a sorted column?
I have complex objects that can be sorted just by custom sorter, so arrow doesn't appear automatic in that case.

**Comment by TonyGermaneri** [comment]
Are you trying to say it _can't_ be sorted by custom sorter?  That seems like a mistake.  The native sort method should be able to sort anything so long as the comparison returns synchronous.

Can you provide an example of your object array and perhaps explain how you sort it normally?

**Comment by anastasi-a** [comment]
Not exactly, it can be sorted by any sorter, but it does it in a wrong way in my case. Because I need to compare not the rows but the objects. So before sorting I need to group rows. 

For example:
`[{
      CountryName: 'France',
      Cities: [
        {
          Name: 'Marseille',
          Codes: ['1', '2', '3']
        },
        {
          Name: 'Paris',
          Codes: ['4', '5', '6']
        }
      ]
    },
      {
        CountryName: 'USA',
        Cities: [
          {
            Name: 'Los Angelos',
            Codes: ['1', '2', '3']
          },
          {
            Name: 'New York',
            Codes: ['4', '5', '6']
          }
        ]
      }]`

After parsing it looks like this http://prntscr.com/ok0upw 
This array has 2 main objects but a lot of rows. When I sort them, I want to move the whole object, but not the row.

I've written method that sorts it correctly, but before that I call `preventDefault` in 'beforesortcolumn' event. And when sort event prevented the arrow in column header cell doesn't appear. That's why I need to find the way to add that arrow so user could understand by which column table was sorted.

**Comment by TonyGermaneri** [comment]
Ah, got it.  So you're not really sorting in the traditional sense, more visually for most columns.  To override or add to the rendering of any cell you can attach to the `afterrendercell` event.  You can shift the text around by altering the `grid.style.columnHeaderCellPaddingLeft` in the event listener.  Then you can draw anything you like on the canvas using `e.ctx`.  The arrows are code, not images, it's up to you how you want to draw it.

This is the arrow code if you want to use code:
https://github.com/TonyGermaneri/canvas-datagrid/blob/master/lib/draw.js#L95

This guy was trying to do something kinda similar #82 might help to see that conversation.

Let me know if that solves the problem.

Cheers,
Tony

**Comment by anastasi-a** [comment]
It solved the problem! Thanks!

**Comment by TonyGermaneri** [comment]
Awesome!
