### ISSUE TITLE
keep scroll position of the selected row

### ISSUE THREAD

**Issue by Hybueno09** [TonyGermaneri/canvas-datagrid#235]
### Expected behavior and actual behavior.
Actual behavior: I clicked a row(index 6), the selected row became high light with border-color style.After a little while, my app received many grid data,but the selected row scrolling below ,also the high light row index is still 6.
In my app,my grid data maybe thousands of row in one page,so i wish keep the selected row and its high light style when received new data, don't affect checking the selected row data..
Can u tell what can i do ,thx very much

### Specifications like the version of the project, operating system, or hardware.
"canvas-datagrid": "^0.22.12"
"electron": "10.16.0"
"react": "16.8.0"

**Comment by TonyGermaneri** [comment]
You can capture the selected rows with this property:
https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.selectedRows

You can set the selected rows with this method:
https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.selectRow

You can detect when changes occur by listening to this event:
https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid#event:selectionchanged

If you listen for selection changes, record elsewhere what the selected rows are, then when you change your data, use selectRow to reselect the desired rows, if they still exist.

I hope that answers your question.

Cheers,
Tony
