### ISSUE TITLE
Canvas doesn't handle keyboard in full-screen mode

### ISSUE THREAD

**Issue by Imperat** [TonyGermaneri/canvas-datagrid#238]
### Expected behavior and actual behavior.
Sometimes it's necessary to turn pages into full-screen mode using full-screen API. (Described here https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen)

When page in full-screen mode has an instance of canvas data grid element it's impossible to select cells using keyboard. Also event "keydown" won't fire.

### Steps to reproduce the problem.
Look at this fiddle: https://jsfiddle.net/nc4gkfz7/1/
It's required to:
1. Open page in full-screen mode and try to navigate on grid using keyboard.

### Specifications like the version of the project, operating system, or hardware.
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Ubuntu 19.04
Canvas Data Grid - 0.22.12

P.S please, have a note that it works good in FireFox

**Comment by Imperat** [comment]
Hi, @TonyGermaneri 
If you have any idea how to fix it, let's discuss. I'm going to think about fixing this bug to avoid workaround in my project.
Thank you!

**Comment by TonyGermaneri** [comment]
It sounds like a input focus issue.  The way input from keyboard is captured is by focusing a sort-of hidden input.  It's sort-of hidden because some browser's won't focus an input if it is completely hidden.  What is the state of the DOM when you're in full screen?  Can you see this "hidden" input?  Is it getting focus?  I'll check out your reproduction later today.

**Comment by TonyGermaneri** [comment]
Ok, I looked at the code, it does look like the input is getting excluded.

And I just discovered github will only show THREE matches when you search.  Lame.

Here: https://github.com/TonyGermaneri/canvas-datagrid/blob/8ebb70d720d957ccd71d0bcbd9d9028d1782f69d/lib/dom.js#L525

The input is added directly to the body.  The documentation says you can access this input via grid.controlInput.  So I'd suggest you move the input into your wrapper when you go full screen. 

`wrapper.appendChild(grid.controlInput);`

But you better put it back in the body when you exit full screen or an error will be thrown and the grid won't get properly torn down on disposal of the instance.  I suppose worse things can happen in the world than that, maybe it won't matter.

Anyhow, that should fix your issue.

Cheers,
Tony

**Comment by Imperat** [comment]
Thanks for your answer, @TonyGermaneri 
It seems you grasp about case when user is unable to open input to start editing cells. I fixed it in my project a long time ago.
In current issue I mean case when user is unable to navigate on grid by clicking buttons (right, left, top, bottom) or also he is unable to work with keyboard. 
I handle `keydown` event in my code to perform actions for undo/redo changes, work with clipboard and other.
I apoligoze for confusing you (denenetly I need to improve my writing English)

**Comment by TonyGermaneri** [comment]
I really hope I'm not mistaken, but I think you're mixing up `input` and `controlInput`.


* @property {object} input - Reference to the the edit cell when editing.  Undefined when not editing.  When editing, this DOM element is superimposed over the cell being edited and is fully visible.


* @property {object} controlInput - Input used for key controls on the grid.  Any clicks on the grid will cause this input to be focused.  This input is hidden above the top left corner of the browser window.


I think your english is pretty good.  I didn't notice you're a non native writer.

**Comment by Imperat** [comment]
ah, I got difference between these inputs.
I'll check the solution what you purposed me.

Thanks a lot, @TonyGermaneri
