### ISSUE TITLE
dragging columns into gutter causes issues with horizontal scroll

### ISSUE THREAD

**Issue by cyrfer** [TonyGermaneri/canvas-datagrid#24]
You can get stuck when scrolling to the right to columns off the screen.

When dragging a column, 
1- drop said column into the column for row numbers (accidentally I guess, one too far to the left),
2- scroll all the way to the right
3- attempt to scroll back to the left will fail with the error below.

```
Uncaught TypeError: Cannot read property 'title' of undefined
    at drawHeaderRow (canvas-datagrid.js:1602)
    at draw (canvas-datagrid.js:1882)
    at scroll (canvas-datagrid.js:2145)
    at Object.set (canvas-datagrid.js:3771)
    at HTMLCanvasElement.scrollWheel (canvas-datagrid.js:3530)
```

discovered with Chrome 58.0.3029.110 (64-bit)

**Comment by TonyGermaneri** [comment]
Work around for now is to right click "clear saved settings".  Will fix as soon as possible.
