### ISSUE TITLE
Multiple filters on single column

### ISSUE THREAD

**Issue by vermadev95** [TonyGermaneri/canvas-datagrid#240]
Need to apply multiple filters on a single column. Is there any option for that or need to create a custom filter?

**Comment by TonyGermaneri** [comment]
Hope this helps:

https://tonygermaneri.github.io/canvas-datagrid/docs/#tutorial--Multiple-filters

**Comment by TonyGermaneri** [comment]
Sorry!  I re-read your question.  Yes, to make more than RegExp matches you will need to create a custom filter.  If you show me your requirements I might be able to help make your filter function.  You can get pretty far with just RegExp.

**Comment by vermadev95** [comment]
I have a string seperated by comma operator. I have formed an array out of that string. I am not sure how to create a RegEx using an array for a single column.
for eg: 
I have an array like ['abc','def'] and I want to filter the data for both the items.

**Comment by TonyGermaneri** [comment]
var myArray = ['abc', 'def'];
grid.filters.myDataType = function (value) {
    return myArray.indexOf(value) !== -1;
}

This assumes the your data is in a column with the data type `myDataType`.  You can also apply filters directly to the schema if you don't want to use data types.

https://tonygermaneri.github.io/canvas-datagrid/docs/#schema

I hope that helps.

Cheers,
Tony

**Comment by vermadev95** [comment]
That did help me apply the filters. Thank you
