### ISSUE TITLE
Question: Formula Support?

### ISSUE THREAD

**Issue by uloskae** [TonyGermaneri/canvas-datagrid#243]
Is there a formula support? ahm, I have a set that needs to interpolate new data like excel or google spreadsheets
Object manipulation is too hard ;c

**Comment by TonyGermaneri** [comment]
There is not.  Adding it isn't too hard if you have a formula lib that you can plug into it.  I've never looked into it myself.  I use the grid to read data out of a database mostly, but I see a lot of people using it to display excel data, which it can do.  Sorry I can't help with that.
