### ISSUE TITLE
performance with amounts of data

### ISSUE THREAD

**Issue by Hybueno09** [TonyGermaneri/canvas-datagrid#245]
I'm using it to build a stock app.
How is the performance to increase 2000 columns to canvas grid table data.At last in one day,it's total `data.length` may be up to 70 million.
Is there any benchmark or anything others .thanks

**Comment by TonyGermaneri** [comment]
2000 columns is no problem.  70 million rows is no problem.  I've tested the grid to over a 1B rows.  The only problem is memory.  You can't have data in every row of the array or your browser will run out of memory.  How you manage swapping data in and out of the array is up to you.

The canvas-datagrid lib does its best[1] to not loop through the items in your array, only using O(1) methods to access and display the data just in time.  This means the size of the data is unbounded from canvas-datagrid.

[1] A single O(n) method is used during initialization, so data size can impact initial display speed.  You can "fix" that by progressively loading data or just putting in a loading message.

**Comment by Hybueno09** [comment]
you said you have tested the grid to over a 1B rows, I wonder how do you solve the memory problem.Did you use some special method to do that,or is there any more detail or demo online.

**Comment by TonyGermaneri** [comment]
2000 columns isn't a problem, so you can keep that in memory.  Define the columns using `grid.schema`.  The 70m*20 is quite a few cells, so you can't have the data in the rows.  You can create empty arrays like this:

```
const list = [];
list.length = 100000000;
```

Then you can remove items from arrays like this:

```
delete list[10048982]
```

This is faster but does not change the array bounds:

```
list[10048982] = undefined;
```

Both methods remove the row from memory.  You need to hook into the `scroll` event, when the user scrolls you can swap data in and out of the array.  The scroll event or data grid will contain the viewport dimensions.

I don't have a demo with the number of rows you are asking for.  But this demo might help: 

https://tonygermaneri.github.io/canvas-datagrid/tutorials/sparklineDemo.html

Relevant Code:
https://github.com/TonyGermaneri/canvas-datagrid/blob/master/tutorials/sparklineDemo.js#L126

This demo shows how you can use the viewport to manipulate the visible data.
