### ISSUE TITLE
How can i hide rows?

### ISSUE THREAD

**Issue by aryxs3m** [TonyGermaneri/canvas-datagrid#246]
I have found **visibleRows** and **isRowVisible** in the documentation, but i didn't found anything about how to hide rows.

Can you give me a short example code?

Thanks.

**Comment by TonyGermaneri** [comment]
You can use filters to remove them from the data set.  But if the user interacts with the filter UX they will be able to remove the filter, you can disable this UX in the options.  You can hide columns, but the user can show them using the UX unless you disable it via options.  You can set a row height to 0, that might kinda hide it, but if you have the "resize rows" UX enabled, the user can expand it, I think it might leave some borders behind too.  

`visibleRows` and `isRowVisible` are used to determine which rows are being painted onto the canvas.  That can be useful when you want to do an action to only the cells/rows that are visible, such as add more to the cell, but these properties are only getters.
