### ISSUE TITLE
Column/Row deselect

### ISSUE THREAD

**Issue by zygimantas** [TonyGermaneri/canvas-datagrid#252]
### Expected behavior and actual behavior.

deselectRow() and deselectColumn() methods should exist to allow deselect the whole column or row programatically.

Sorry if I've missed the functionality in docs.

**Comment by TonyGermaneri** [comment]
It's part of the select methods.  You just need to pass the right arguments to them.  Pass true to the argument `ctrl`, that will cause it to toggle on and off.  There are a few other ways to do it.  You can also set the selected rectangle for simple selections.  For more complex selections, you can use `grid. selections`.  It is a getter setter so you can read in the selection, and manipulate it, then set it back to get a jagged selection.  Each method solves a specific use case.  There are a few other ways, let me know if you want me to list off some more options.

https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.selectArea

https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.selectColumn

https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.selectRow

**Comment by zygimantas** [comment]
Thanks Tony, well, I've tried `ctrl`  argument without luck. My case is:

```
grid.addEventListener('click', e => {
  this.grid.selectRow(e.cell.rowIndex, true);
})
```

Issue 1: second click on the same cell does not deselect the row
Issue 2: (probably Angular related issue), but after a click, active cell is selected, but the row becomes selected only after a mouse move.

**Comment by TonyGermaneri** [comment]
Issue 1: It looks like the code will just toggle the selection, which is what CTRL does.  Seems like if you're trying to ensure it is not selected on click, if it is not selected you can call e.preventDefault() to stop it from selecting the column.  I know, I know, it's starting to look like there should be explicit deselect methods, or at least better arguments to these methods.

Issue 2: Sounds like you just need to call `grid.draw()` right after.  It's canvas based, so not everything will trigger a redraw, some methods that should don't.
