### ISSUE TITLE
Scrolling with arrow keys inside the grid is not working in  IE 11

### ISSUE THREAD

**Issue by baland** [TonyGermaneri/canvas-datagrid#257]
### Expected behavior and actual behavior.

In IE 11 arrows keys do not work  - internal scrolling is not occurring.  

This is happening because Number.IsNaN is not implemented for IE.   The solution is easy:  simply define Number.IsNaN if not currently defined or use different isNaN.  

### Steps to reproduce the problem.

click on any cell and then apply arrow keys - the keypresses are ignored

### Specifications like the version of the project, operating system, or hardware.

0.22 and prior.

**Comment by TonyGermaneri** [comment]
Does anything ever work in IE11?  Sorry, it's really hard to test for, this happened before.  Thanks for finding the bug.  Sounds like an easy fix, glad you found that too!  👍

**Comment by baland** [comment]
I know.  IE adds a whole new meaning to the term “busy work”.  I’m
surprised IE is still perfectly legal to use in most municipalities :)

**Comment by ndrsn** [comment]
Hi, I'm closing this issue as we've decided to drop IE11.
