### ISSUE TITLE
Not rendering in tabs.

### ISSUE THREAD

**Issue by Kumar-Kishan** [TonyGermaneri/canvas-datagrid#258]
### Expected behavior and actual behavior.
Expected Behaviour: Datagrid to render in tab
Actual Behaviour: Datagrid renders in only one of the tab

### Steps to reproduce the problem.
JSFiddle Link: https://jsfiddle.net/Kishan219/akwu0x2c/

**Comment by TonyGermaneri** [comment]
See:

https://jsfiddle.net/gy74nab2/2/

```
<div id="app">
     <b-tabs lazy>
            <b-tab title="First">
                <canvas-datagrid ref="grid1" :data.prop="items1"></canvas-datagrid>
            </b-tab>
            <b-tab title="Second">
                <canvas-datagrid ref="grid2" :data.prop="items2"></canvas-datagrid>
            </b-tab>
    </b-tabs>
</div>
```

Hope this helps!
Cheers

**Comment by TonyGermaneri** [comment]
By the way, you can persist the user settings (column size, etc.) by giving the grids unique name attributes.  Make sure you use a unique name per grid or they'll try and share persisted values.
<canvas-datagrid name="grid1"/>

**Comment by Kumar-Kishan** [comment]
Thanks. It worked. But can I make the grid work in non-lazy context or not?

**Comment by TonyGermaneri** [comment]
Very sorry about lazy, I was taking the opportunity to learn about b-tabs, nothing to do with your problem I think.  Should work lazy or not lazy.

**Comment by Kumar-Kishan** [comment]
@input method is provided in b-tabs. And we can resize on nextTick in the input method. Thanks for the solution
