### ISSUE TITLE
aggregate property in format part of schema

### ISSUE THREAD

**Issue by dogoku** [TonyGermaneri/canvas-datagrid#259]
First, since this is the first time writing a question, let me say:  **your library is amazing**

I was going through your [demo](https://tonygermaneri.github.io/canvas-datagrid/tutorials/demo.html) and digging into the column schema when I noticed this

![image](https://user-images.githubusercontent.com/761999/79000384-1749d880-7b7f-11ea-881b-34cdbe251721.png)

I searched in docs, in the source of the demo and in github issues but I couldn't find any reference of aggregate or aggregation (except one issue about grouping by column, which you can say is related)

Was that just left over code from an unfinished feature or just a bad copy pasta 🍝?

Thanks 👍

**Comment by TonyGermaneri** [comment]
I'm like 82% sure that is not part of my schema.  I think you have an object merged into the column schema that has enough in common with the schema that it still works, which is super cool.

There's proposals to do aggregates, but I think it's outside of the scope of the project.  It's pretty easy to implement something like that, I can show you how if you like.  Basically add an artificial row of data at the bottom of your normal data that has totals of the columns and/or selected data.  Sounds fun.

Another way to do it would be to add another grid instance just below the current one and match the scrollLeft properties when they scroll, maybe hide some of the bars.

I am happy to help implement and fix things.  I'm always around to answer questions, there's a slack channel I'm in 24/7 for this project.

**Comment by dogoku** [comment]
Thanks for the fast reply 👍

> I'm like 82% sure that is not part of my schema. I think you have an object merged into the column schema ...

But that screenshot was taken on the demo page.
https://tonygermaneri.github.io/canvas-datagrid/tutorials/demo.html

So unless a Chrome extension is injecting that somehow, it couldn't have been me.

> I am happy to help implement and fix things. I'm always around to answer questions, there's a slack channel I'm in 24/7 for this project.

I have some ideas around filtering, aggregation and grouping, and I agree that they may be outside of the scope of this project, but thanks for the offering to help :)

**Comment by TonyGermaneri** [comment]
Indeed they are being injected by another system then.  This is the data.gov format.  It's close enough to the schema format where it just works.

**Comment by TonyGermaneri** [comment]
Here's a link to other data.gov sources: https://catalog.data.gov/dataset?res_format=JSON&_res_format_limit=0&_bureauCode_limit=0. I think anything in there that is JSON format will work in the mapper on the demo page.  Just find the data source URL and set it to the q query string parameter of the page:

e.g.: "Accidental Drug Related Deaths 2012-2018"

https://tonygermaneri.github.io/canvas-datagrid/tutorials/demo.html?q=https://data.ct.gov/api/views/rybz-nyjw/rows.json?accessType=DOWNLOAD
