### ISSUE TITLE
defaultValue not passing row index to function

### ISSUE THREAD

**Issue by BluestCloud** [TonyGermaneri/canvas-datagrid#265]
### Expected behavior and actual behavior.
The documentation for the defaultValue function in the schema says `The arguments passed to this function are: argument[0] = canvasDatagrid.header, argument[1] = row index.`

I tried that with a function with two parameters, but only the header appears to be passed, and the row index parameter is showing up as undefined.

Looking at the code in intfs.js, it looks like only the header object is being passed and not the row index.

 ```
self.applyDefaultValue = function (row, header) {
            var d = header.defaultValue || '';
            if (typeof d === 'function') {
                d = d.apply(self.intf, [header]);
            }
            row[header.name] = d;
        };


```
### Steps to reproduce the problem.
```

var grid = canvasDatagrid({
    parentNode: parentNode,
    data: [
        {col1: 'foo', col2: 0, col3: 'a'},
        {col1: 'bar', col2: 1, col3: 'b'},
        {col1: 'baz', col2: 2, col3: 'c'}
    ]
});
grid.addColumn({
    defaultValue: function (e,r) {
        console.log(r); //Will return undefined instead of row index
        return new Date().toString();
    },
    title: 'Bar',
    type: 'date',
    name: 'bar'
});
```

Is there a workaround for this?

**Comment by TonyGermaneri** [comment]
That's not good.  Yeah, you should be able to get the row number from `grid.data.length` since the new row is always the last row.  If that doesn't work, let me know, there's likely a few other ways, like grid.selectedRows.

**Comment by BluestCloud** [comment]
I am trying it on an insertColumn, not a new row, so it's not always the last row.

I tried changing `d = d.apply(self.intf, [header]);` to `d = d.apply(self.intf, [header,row]);`, and I think I am getting the row, trying to get a row index so I can pass that instead.

**Comment by TonyGermaneri** [comment]
I'm so sorry, somehow I read the title as "not passing new row index" when it quite clearly does not say that.

Your assessment is correct.  Depending on how the action was invoked, you can potentially use the [activeCell](https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#canvasDatagrid.activeCell) values.

It is obviously a bug, so a PR is welcome.  You've already identified the problem, I bet it's easy to fix.
