### ISSUE TITLE
data export to xls

### ISSUE THREAD

**Issue by huangwei16800** [TonyGermaneri/canvas-datagrid#268]
have function, export data to xls?

**Comment by TonyGermaneri** [comment]
You can use copy/paste, but there's not a built in function for exporting data.  It's not hard to make it produce a CSV file you can import into excel.   Look up "data url file download" and you'll find tutorials on how to turn your JSON data into a file that can be downloaded by the browser.

I just ran the search and this seemed like a good resource: https://stackoverflow.com/questions/3916191/download-data-url-file

Good luck!
