### ISSUE TITLE
Display asynchronous results in a cell, after the initial cell value is parsed (e.g. when applying a formula)

### ISSUE THREAD

**Issue by loredanacirstea** [TonyGermaneri/canvas-datagrid#278]
I am trying to add a formula system, so I need to modify the cell content. Some of the formula operations are asynchronous.
So, I have two questions:
1) is there a more appropriate/efficient event than `afterRenderCell` to modify cell content?
2) how can I do this modification in an async way?

### Expected behavior and actual behavior.

I could only use the `afterRenderCell` event to change the initial content of the cell by changing `innerHTML`, but it is very computation heavy because it is triggered on hover - which I did not expect.
I tried `datachanged`, but the `innerHTML` changes are not persisted.

### Specifications like the version of the project, operating system, or hardware.

`canvas-datagrid 0.22.13`

(I would have joined the Slack channel, but I don't see a way to message you. My email is on my GitHub profile.)

**Comment by TonyGermaneri** [comment]
You can just change the `grid.data` value or modify the object reference you have set to it.  If your data gets changed at a granular level you might have to call [https://tonygermaneri.github.io/canvas-datagrid/docs/#canvasDatagrid.draw](grid.draw), but there is an observer looking to see if you have changed data so it can refresh the data.

Hope this helps!

**Comment by loredanacirstea** [comment]
I couldn't replace `grid.data` because I am using formulas that are executed in an async way. So, I need both the initial formula/expression string and the value.

So: I handled my async operations outside the datagrid. I keep a map of cell keys (e.g. `A1`) and their values (retrieved asynchronously) and pass them through formatter functions each time the grid is re-rendered.
From my perspective, this issue can be closed, thank you.
