### ISSUE TITLE
getColummnWidth is not publicly available

### ISSUE THREAD

**Issue by hbooth** [TonyGermaneri/canvas-datagrid#281]
### Expected behavior and actual behavior.
getColummnWidth a valid function (per documentation)

### Steps to reproduce the problem.
attempt to call getColummnWidth(0) on a newly instantiated datagrid

**Comment by hbooth** [comment]
need the following code in lib/intf.js around line 527

```
self.intf.getColummnWidth = self.getColummnWidth;
```

**Comment by TonyGermaneri** [comment]
So sorry, you're absolutely right.  Looks like the method name is not spelt correctly either.  Might want to fix both at the same time since nobody can implementing it yet.
