### ISSUE TITLE
When the 'canvas-datagrid' is used with 'golden-layout', there is a problem with the display style. When dragging the subpage window, the 'canvas-datagrid' will crash.

### ISSUE THREAD

**Issue by yuanliwei** [TonyGermaneri/canvas-datagrid#282]
### Expected behavior and actual behavior.
Expect "grid" to display normally

### Steps to reproduce the problem.
[mmk.zip](https://github.com/TonyGermaneri/canvas-datagrid/files/4987107/mmk.zip)

open index.html in browser, drag item title.

![screen-capture](https://user-images.githubusercontent.com/15871845/88643625-81699780-d0f4-11ea-9b86-f3f8396b8fad.gif)

### Specifications like the version of the project, operating system, or hardware.
0.22.16

**Comment by yuanliwei** [comment]
Fixed.

**Comment by TonyGermaneri** [comment]
Nice work!
