### ISSUE TITLE
 Does integration with SheetJS support styles?

### ISSUE THREAD

**Issue by tactycadmin** [TonyGermaneri/canvas-datagrid#312]
I use SheetJS to parse an excel file and render to html on my React app. I'd like to use canvas to do the rendering so I can benefit from other features such as cell selectios etc. Is it possible for canvas to render a sheetJS json output WITH styles?

**Comment by ndrsn** [comment]
While we do not support directly rendering styled cells from a SheetJS data object, you can hook into the rendering of cells by adding an event listener for either `rendertext` or `rendercell`, and determine your styling by modifying the canvas context (untested code):

```js
function getCellCanvasStyle(rowIndex, columnIndex) {
  // ... conditional logic to determine style

  // default
  return { fillStyle: '#ffffff' };
}

function getCellTextCanvasStyle(rowIndex, columnIndex) {
  // ... conditional logic to determine style

  // default
  return { fillStyle: '#000000' };
}

grid.addEventListener('rendercell', handleRenderCell);
grid.addEventListener('rendertext', handleRenderCellText);

function handleRenderCell(event) {
  const style = getCellStyle(event.cell.rowIndex, event.cell.columnIndex);

  if (style) {
    Object.assign(e.ctx, style);
  }
}

function handleRenderCellText(event) {
  const style = getCellStyle(event.cell.rowIndex, event.cell.columnIndex);

  if (style) {
    Object.assign(e.ctx, style);
  }
}
```

Does this make sense?
