### ISSUE TITLE
SCRIPT438: Object doesn't support property or method 'attachShadow' on IE11

### ISSUE THREAD

**Issue by yogesh-onlinerti** [TonyGermaneri/canvas-datagrid#329]
Not working on IE11, even official demo gives error - "SCRIPT438: Object doesn't support property or method 'attachShadow'". 

added webcomponents libraries (webcomponents-shadydom@1.8.0, webcomponents-custom-elements); this solves above issue but still datagrid won't load.

**Comment by WebMex** [comment]
The official demo doesn't work with Edge 18
![Screenshot 2021-01-12 at 10 11 01](https://user-images.githubusercontent.com/3994338/104294261-45b66480-54bf-11eb-9f51-d3f974941107.png)

**Comment by ndrsn** [comment]
Hi, I'm closing this issue as we've decided to drop support for IE11.

@WebMex , thanks for your report — I'll open a new issue to look into Edge.
