### ISSUE TITLE
Question: Multiple column sort

### ISSUE THREAD

**Issue by jelmerveen** [TonyGermaneri/canvas-datagrid#343]
After looking through the documentation and using the demo's, but could not find an answer.

Is there a way to do a 'then by' sort?

So I want to sort on column1, then by column2

Is that possible?

**Comment by ndrsn** [comment]
Hoi Jelmer, I'm afraid there's no way to do so currently through the interface, but you may be able to do it yourself. 

[getFilteredAndSortedViewData](https://github.com/TonyGermaneri/canvas-datagrid/blob/ee5c345492badf1fbd9f35e6999c7736676db31a/lib/intf.js#L300) is the function that actually sorts the data. It calls a `sortFunction` which is ordinarily determined by the column schema, but you can pass in a custom sort function to  [grid.order](https://github.com/TonyGermaneri/canvas-datagrid/blob/ee5c345492badf1fbd9f35e6999c7736676db31a/lib/publicMethods.js#L715) which then determines how to sort.

The next step then would be to get that working in the UI. I'm not 100% sure this would work, but I'm thinking by adding a `click` event listener on headers (e.g. a shift+click will add sorting for that column while keeping the other sorting intact), you could update your custom sort function, and pass it to `grid.order` to have it refresh the view.

**Comment by jelmerveen** [comment]
Thank you very much for your pointers @ndrsn !
I'll take a look

**Comment by ndrsn** [comment]
Sure! Feel free to reach out, I'd be happy to help.
