### ISSUE TITLE
Typescript declaration does not work well

### ISSUE THREAD

**Issue by dinfer** [TonyGermaneri/canvas-datagrid#353]
### Expected behavior and actual behavior.
Exports valid typescript types.

### Steps to reproduce the problem.
1. generate a typescript react project
2. Install this package using yarn `yarn add canvas-datagrid`
3. Import the library using `import DataGride from "canvas-datagrid";`
4. go the error below

![image](https://user-images.githubusercontent.com/11496403/115950070-acf6a280-a50b-11eb-9887-db46e126e453.png)

![image](https://user-images.githubusercontent.com/11496403/115950108-e3ccb880-a50b-11eb-8beb-30cd81675164.png)

### Specifications like the version of the project, operating system, or hardware.

canvas-datagrid@^0.3.4:
  version "0.3.4"
  resolved "https://registry.npmjs.org/canvas-datagrid/-/canvas-datagrid-0.3.4.tgz#b5c6ecc281ec70f474a6fe35d2625ba8d67e7d31"
  integrity sha512-oTXeqtbIMrV6LL+bo8qPmem5TMgvtY9ewwMkJgBNjlhjUjeSuFDl3+0bMSsQCmuIkET4c9QlzNDDRgFOpHfMiw==
  dependencies:
    is-printable-key-event "1.0.0"

**Comment by nipatiitti** [comment]
@dinfer Did you find any workarounds? I'm also struggling with the same problem

**Comment by nipatiitti** [comment]
I did some fumbling around and turns out the problem was the way I imported the library. 
So instead of 
```javascript
import canvasDatagrid from  'canvas-datagrid'
```
Just use 
```javascript
import 'canvas-datagrid'
```
And it will work. Alternatively you can just add canvas-datagrid to your tsconfig.json types array
