### ISSUE TITLE
I found a bug：when the canvas-grid is destroyed，the input box is not destroyed together

### ISSUE THREAD

**Issue by cyulin** [TonyGermaneri/canvas-datagrid#354]
### Expected behavior and actual behavior.
This is a great project. 
I found a bug：when the canvas-grid is destroyed，the input box is not destroyed together

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/canvas-grid-issue-rr88k?file=/src/App.js:186-203)

### version of the project
| Environment | Info |
|---|---|
| canvas-grid| latest |

**Comment by dinfer** [comment]
I found the problem too. The dispose method does not remove the input element. I have to remove input element manually.
I'm finding alternative library, Have you some good idea ?

**Comment by itgoldman** [comment]
you can call
`$(grid.input).remove();`
before
 `grid.dispose();`
