### ISSUE TITLE
Version 0.3.5 can't find the dist folder

### ISSUE THREAD

**Issue by cyulin** [TonyGermaneri/canvas-datagrid#367]
### Steps to reproduce the problem.
![image](https://user-images.githubusercontent.com/10137410/129528860-f21b5982-d214-4438-af28-a19ca641ac27.png)
![image](https://user-images.githubusercontent.com/10137410/129528902-8236ad01-1a10-4562-9e2c-08757c87e8a0.png)

**Comment by TonyGermaneri** [comment]
Sorry about that.  Please try module v0.3.6.

**Comment by cyulin** [comment]
thanks
