### ISSUE TITLE
Move multiple columns or Rows

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#390]
It would be great to have the ability to drag multiple columns (or Rows) when multiple are highlighted.

![image](https://user-images.githubusercontent.com/909771/140593205-253b0fca-97f1-440b-ad7d-399ebcccfa82.png)

Here is an example: example: https://gyazo.com/d32dfc66affb9b5de97fff1cbdb39a8b.

**Comment by ndrsn** [comment]
I agree, this fits with our general aim to be more Excel/Sheets-like. @TonyGermaneri, any opinions on this?

**Comment by hiro00125** [comment]
Hello
Can I work with you?

**Comment by hiro00125** [comment]
I've just found out this issue on Upwork.
I'd like to help you.

**Comment by david542542** [comment]
@hiro00125 once you delete all your comments, you can email me at deemarklit@gmail.com and we can follow up there regarding potential work.
