### ISSUE TITLE
Row-artifacts when sorting a column

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#391]
Sometimes the sort adds some odd artifacts to the rows. 

![image](https://user-images.githubusercontent.com/909771/140593228-04dd41aa-94be-4d35-b3f0-68b0578f0236.png)

For example: https://gyazo.com/235b23c3652e59fb5c7de19d20a12d4c.

**Comment by ndrsn** [comment]
This is definitely a bug. I'll look into this over the weekend, probably not a big deal.

**Comment by ndrsn** [comment]
The logic for this is in https://github.com/TonyGermaneri/canvas-datagrid/blob/143d356bc5bfd141979f868a917ebfc00a74be1d/lib/draw.js#L1106 — not sure if the logic is no longer sound, or bound row to view row mapping isn't updated correctly

**Comment by ndrsn** [comment]
Ah, OK, it seems to make sense: when you're sorting, the `boundRowIndex` isn't necessarily contiguous from one row to the next, causing the gap to be shown `hasRowGap = true`. An indicator like this isn't particularly useful, so I'll add a provision to exclude the rowGap from being rendered when sorting is active.
