### ISSUE TITLE
Highlighting incorrect column after repositioning column

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#392]
The highlighted column(s) does not stay highlighted after repositioning it in the interface. 

![image](https://user-images.githubusercontent.com/909771/140593284-9dbd4221-bd26-4124-9f61-25adb4c9d727.png)

For example: https://gyazo.com/5cac78e05e1158638a1e6c9c6ec75c0e.

**Comment by ndrsn** [comment]
Holy mackerel, that's a bug!

**Comment by xianzhi3** [comment]
@ndrsn I fixed the bug in the source code. how can I do a pull request on the repo?

**Comment by ndrsn** [comment]
Please read the [GitHub documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) for these types of questions
