### ISSUE TITLE
Position of scroll-bar with a frozen pane

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#393]
When there is a frozen pane, it seems like the scroll-bar positioning is off. It should only allow going up to the frozen pane, since the frozen area is not part of the scroll.

![image](https://user-images.githubusercontent.com/909771/140593336-83c0a398-d547-48a5-b57d-4364037924fb.png)

For example: https://gyazo.com/93c2baba5d2cdd924ce65fe9f81a8eab.

**Comment by ndrsn** [comment]
Nice catch — that's sloppy, we should fix it. I'll see if I can look into it this weekend.
