### ISSUE TITLE
Moving a row screws up the row-highlighting

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#394]
Often when a row is moved, the selectability of rows/cells doesn't act as expected. 

![image](https://user-images.githubusercontent.com/909771/140593411-9b6218fa-a7ae-4699-965c-1be30cdfe127.png)
![image](https://user-images.githubusercontent.com/909771/140593423-e4d6ea2f-e563-493d-9d73-d4a452cb17fb.png)
![image](https://user-images.githubusercontent.com/909771/140593442-e14e7216-76c6-445c-aa67-e943cc099b28.png)
![image](https://user-images.githubusercontent.com/909771/140593450-65437edd-4e9a-49a1-8749-1503166fb1b7.png)

For example: https://gyazo.com/4dde8cf953dc9ec7502fc182fecee37d

**Comment by ndrsn** [comment]
Totally weird, this looks like something recent. Major buggy, thanks for reporting. Will look into.
