### ISSUE TITLE
Ability to create a grouping of rows or cols.

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#397]
Similar to the ability to create trees, it would be great to allow the creation of row-groups or col-groups. 

![image](https://user-images.githubusercontent.com/909771/140799711-c54119e2-020c-4ff9-a30a-7f286b5a2cb8.png)

For example: https://gyazo.com/8b848eec84fe8f1192363941663ec51b

**Comment by david542542** [comment]
@hangxingliu can you close this issue now?

**Comment by hangxingliu** [comment]
> @hangxingliu can you close this issue now?

Yep, It can be closed now, but I have not permission to close this issue
