### ISSUE TITLE
Possible to create a 'button' within a cell?

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#398]
In Excel and Google Sheets a 'button' is often used for a context menu related to a heading, for example:

![image](https://user-images.githubusercontent.com/909771/140803689-adb63c84-7af1-421e-ac99-a6f3a4f123a8.png)

Does canvas-datagrid currently support this, or is it something that would need to be added as a new feature? If it's something that's already supported, could we add an example of it to the [Tutorials](https://canvas-datagrid.js.org/#tutorials) section?

**Comment by ndrsn** [comment]
It's not supported out of the box, but you can hook into the `afterrendercell` event to draw your own 'button' on top of the canvas. [Here's a crude example](https://replit.com/@ndrsn/ThreadbareReadyPagerecognition#script.js) (it's a box not a button, but you get the idea):

<img width="848" alt="CleanShot 2021-11-12 at 14 17 44@2x" src="https://user-images.githubusercontent.com/950979/141473269-d15e6243-a73f-4f84-88f8-254fbd8b4f9b.png">

```js
grid.addEventListener('afterrendercell', (event) => {
  if (event.cell.rowIndex === -1 && event.cell.columnIndex > -1) {
    drawButton(event.ctx, event.cell);
  }
});
```

Obviously, you'd want to make it actually look like a button, render differently on hover or active states, but what this looks like depends a little bit on what the rest of your application looks like — I don't think canvas-datagrid should be too opinionated in terms of UI look and feel, or you lose flexibility when integrating.

Alternatively, you could use HTML buttons. I have the same issue: I also want to show filter buttons like Excel, and canvas drawing seems cumbersome, so this is the route I've wanted to investigate, but haven't gotten around to yet.

**Comment by hiro00125** [comment]
Hello
Can I work with you?
I've just found out this issue on Upwork.

**Comment by david542542** [comment]
@hiro00125 delete this comment (and the other one) and apply directly, please.

**Comment by david542542** [comment]
@xianzhi3 here are two more examples of where a button could be used: https://gyazo.com/905512e26cb23f9458d3a2fc66532fcb. In other words, it would be great to be able to arbitrarily position and style the buttons (ignore what they produce after clicked).

**Comment by david542542** [comment]
@xianzhi3 + @ndrsn the button looks good. Can you do two demo examples on code-sandbox, one where the buttons are at the top of a table, and the other where there's just a one-off button (like you copy-paste example) and then I think this is ready for a PR. Nice work.

**Comment by david542542** [comment]
![image](https://user-images.githubusercontent.com/909771/144511376-30a8cb0d-69e2-48b0-8464-5b5b95f3090c.png)

**Comment by xianzhi3** [comment]
I created a PR

**Comment by ndrsn** [comment]
Ah whoops I closed this by accident; have not seen an example yet of the second case.

**Comment by david542542** [comment]
What's the second case? It should cover both I just tested them: https://gyazo.com/792000cb8dacd9d3c84f222a16be51a3

**Comment by ndrsn** [comment]
Ah, apologies — didn't see the other one. Not necessarily relevant for this particular issue, but is there a way to remove the button, as well?

This is the behavior I'm seeing:

![CleanShot 2021-12-04 at 22 13 05](https://user-images.githubusercontent.com/950979/144724752-8c56900a-d693-4512-a3dc-8361919c7766.gif)

**Comment by david542542** [comment]
Oh yea good catch, let’s pls fix that Xianzhi, or at least expose a handler
to deal with it.

**Comment by ndrsn** [comment]
While you guys are at it, I noticed that not all areas of the button seem to activate the dropdown:

![CleanShot 2021-12-05 at 00 01 03](https://user-images.githubusercontent.com/950979/144727193-9b4791f9-edc4-4553-8bd7-9eba033f9605.gif)

Not a biggie, though.

**Comment by david542542** [comment]
Yes exactly. Good call!

**Comment by xianzhi3** [comment]
@ndrsn + @david542542 I fixed the bugs. Can you check it at the site https://90zfd.csb.app/?

**Comment by xianzhi3** [comment]
@ndrsn I created a PR for the changes
