### ISSUE TITLE
cellAlignment not seems to work on right

### ISSUE THREAD

**Issue by alonir** [TonyGermaneri/canvas-datagrid#400]
Hi,

### Expected behavior and actual behavior.
When passing style: {cellAlignment: right} on initial 
expecting the text to be right to left, actually nothing changed.

### Steps to reproduce the problem.
let cDg = canvasDatagrid({ parentNode:HTMLOUT, data:data ,style: {cellAlignment: right} });

### Specifications like the version of the project, operating system, or hardware.
Using Chrome  and latest version of canvas-datagrid

**Comment by ndrsn** [comment]
Do you mean `cellHorizontalAlignment` ? See https://canvas-datagrid.js.org/#canvasDatagrid.style.cellHorizontalAlignment
