### ISSUE TITLE
Freeze-pane fixes

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#403]
There are a few small bugs or improvements that can be made to the frozen row/col guideline. Here they are:

A. It seems to interfere with dragging and dropping cols/rows. For example: https://gyazo.com/d9b43f796e5fa256a5c36cfac29e5b75. The frozen gridline should be ignored/inactive when moving another object (be it a cell, range, header, row).
B. The rows/cols should not 'jiggle' at all. Take this example comparing it to Google Sheets: https://gyazo.com/295e0870d4ae5ff4945cc08955df1acc. Only after the frozen gridline is 'released' does the positioning of the cols/rows and scroll bar update.
C. The position of the gridline should update after it's at the midpoint of the next/prev col/row, not when it's at the start. Here's an example: https://gyazo.com/0b67a27bbd224259ae97ff201e17aac1.

If there are no objections here, perhaps we can just use Google Sheets as a good reference for how the frozen pane/gridline should work?

**Comment by ndrsn** [comment]
I'm totally on board with all of these points!

**Comment by david542542** [comment]
One additional thing I noticed is when you re-size a column next to a frozen pane it becomes 'empty' until it is moved. I believe Point B should fix this above, but please check this case as well. For example: https://gyazo.com/770572fa3230599323f5593e03514aac.

![image](https://user-images.githubusercontent.com/909771/143366633-4339c888-acbd-449f-b458-59073c7fead4.png)
