### ISSUE TITLE
Size-to-fit ellipses option

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#407]
When double-clicking a column to resize it, it will resize it to the data underneath the column heading. However, if the column heading is very long, that may not be completely shown. I think there should be an option when setting up the grid for the `autoResizeIncludesHeading` or something like that. For example: https://gyazo.com/7a589b2262d30ef9eda9d7a4e70b92d1

**Comment by ndrsn** [comment]
Agreed, I think the default should be `true` (as in Excel).

**Comment by ndrsn** [comment]
Whoops, not sure https://github.com/TonyGermaneri/canvas-datagrid/commit/74650021f111133ac3b54688907eb406a99f88a2 actually fixes this issue; reopening until time to confirm.
