### ISSUE TITLE
Performance suffers on Firefox

### ISSUE THREAD

**Issue by shahthepro** [TonyGermaneri/canvas-datagrid#42]
The grid feels too slow on Firefox. However it is fast on Chrome and IE. 

https://tonygermaneri.github.io/canvas-datagrid/tutorials/demo.html

Can you optimize it for Firefox?

**Comment by TonyGermaneri** [comment]
I haven't profiled it in FF yet.  I'll see what I can do.

**Comment by TonyGermaneri** [comment]
It's some weird mode for mouse wheel use.  Apparently it's related to "delta wheel event mode" whatever that is.  I'll have it fixed in the next release (a few days at most).  https://stackoverflow.com/questions/39374201/mouse-wheel-events-deltas-and-delta-modes.
