### ISSUE TITLE
Ability to hide rows/cols

### ISSUE THREAD

**Issue by david542542** [TonyGermaneri/canvas-datagrid#420]
It seems there is the ability to toggle the visibility of a column currently, however, it would be nice to have the Excel/Sheets-like ability to have a grouping of cols or rows that can be hidden or un-hidden. Here is an example: https://gyazo.com/dd110fa965ac74645b4e264c73eea4f4. Note that contiguous selections are collapsed/merged together.

![image](https://user-images.githubusercontent.com/909771/143397493-094e36b6-c80e-4efd-b222-28df32e72b0c.png)

**Comment by david542542** [comment]
@hangxingliu can I close this issue now?

**Comment by hangxingliu** [comment]
> @hangxingliu can I close this issue now?

Yep, The PR about this issue has been merged
