### ISSUE TITLE
Autocomplete filter not working in IE11

### ISSUE THREAD

**Issue by TonyGermaneri** [TonyGermaneri/canvas-datagrid#47]
`SCRIPT445: Object doesn't support this action contextMenu.js (281,1)`.  The only "unusual" thing around there is an event dispatcher.  I'm guessing IE11 does not support `HTMLElement.dispatchEvent(new Event('keyup'));`  It can be raised in another way that should work with new and older browsers.

**Comment by ndrsn** [comment]
Dropped support for IE11.
