### ISSUE TITLE
Cannot sort when grid.formatters function has a custom name?

### ISSUE THREAD

**Issue by pcross42** [TonyGermaneri/canvas-datagrid#487]
Sorting in the tutorial does not work when the column type and function is renamed from "date" to "mydate".

To have two different date formats for different columns (say a full date, and then only the year and month or whatever), the two grid.formatters functions need two different names, they can't both be called "date". After the column type and matching function name is changed, the column still displays correctly, but the sort no longer works:    _Cannot sort type "mydate" falling back to string sort_.

**Steps to reproduce the problem.**
In the [Format-data tutorial,](https://canvas-datagrid.js.org/#tutorial--Format-data), change "date" to "mydate" (in two places), then click to sort.

name: 'col2',
            type: '**mydate**'

...

grid.formatters.**mydate** = function (e) {
    return new Date(e.cell.value).toISOString();
};

**Comment by hangxingliu** [comment]
You can give a property named `sorter` to the column `col2`. Its signature is `sorter(string columnName, string direction)`. And it returns a function to sort the column. 

Here is an example:
``` javascript
sorter: (col, dir) => {
    if(col !== 'col2') return;
    if(dir === 'asc')
        return (a,b) => a.col2 - b.col2;
    else
        return (a,b) => b.col2 - a.col2;
}
```

**Comment by pcross42** [comment]
Ah! Thank you. I think I get it: a custom formatter called 'mydate' requires a custom sorter function, whereas a formatter called 'date' presumably has a sorter already called 'date' by default.

Adding your snippet in the tutorial (preceded by a comma) after "type: mydate" indeed fixes the sorting.

It also worked for me as an alternative to add a sorter called mydate, in lines below the existing tutorial code:

```
grid.sorters.mydate = function (columnName, direction) {
    var asc = direction === 'asc';
    return function (a, b) {
        if (asc) {
            return a[columnName] - b[columnName];
        }
        return b[columnName] - a[columnName];
    };
};
```
