### ISSUE TITLE
Some parts are missing in the document page

### ISSUE THREAD

**Issue by xingming2020** [TonyGermaneri/canvas-datagrid#495]
The end of the document page is the hideColumns method. The events, style, and tutorials sections are missing.

**Comment by ndrsn** [comment]
Yeah, I just noticed this myself — looking into it... Thanks for reporting!

**Comment by hangxingliu** [comment]
It causes by that these parameter doesn't contain description

<img width="401" alt="Screenshot 2022-02-24 at 11 30 10" src="https://user-images.githubusercontent.com/4303130/155452689-8c300519-a1cb-4114-903e-7dbfda8d45e8.png">

**Comment by ndrsn** [comment]
That seems to have fixed it — thank you @hangxingliu for the quick analysis, and @xingming2020 for reporting!
