### ISSUE TITLE
Copy/Paste functionalities

### ISSUE THREAD

**Issue by lubianm** [TonyGermaneri/canvas-datagrid#50]
First of all, I really appreciate the great job you're doing with this fast and nice grid.
Do you plan to add a copy/paste functionality on the grid (I've seen that "copy" works fine, but "paste" don't) ? Do you think it will be possible to have on the bottom-right corner of the cell(s) an icon to drag the current content on multiple cells (horizontally or vertically) ? I've looked for these features on your documentation but I've not found it, maybe I missed it ?

**Comment by TonyGermaneri** [comment]
I'll add the two features you're describing.  I've had some other informal requests for the same.  Sorry for the late response.  I was rewriting the mobile UX and was trying not to look at the internet at all.  The handle feature is in conflict with the mobile UX, mobile UX provides 4 handles on each corner of the cell that allows for altering the selection.  But I'm ok with mobile not having the ability to drag and drop other cells for now, it seems overly complex for a touch interface, so this feature will not be available mobile.

I'll add these features:

**Functions**

- paste(x, y, data)
- move(x1, y1, x2, y2)

**UX**

draw square in the lower right corner of the lowest rightmost selected cell that when mousedown'ed engages a draggable dashed outline the same shape as the data, that when dropped engages a "move" of the data from x1,y1 to x2,y2.

**Comment by TonyGermaneri** [comment]
Everything but cut is now implemented.  Cut should be implemented sometime this week.  The behavior isn't exactly what was planned, but is more intuitive.  When you have the attribute `borderDragBehavior` set to `move` and `allowMovingSelection` set to `true` then you can move the selection around by clicking and dragging on the border of a selection.  When you hover over a selection border your mouse cursor will change to the "grab" cursor indicating you can begin the drag operation.

Two new public methods were added.  moveTo(selection, x, y) and moveSelection(offsetX, offsetY).  Both were required to implement the new feature.  In addition, I refactored the clipboard implementation to be more in accordance with the W3C spec.  Now you can set `clipboardMimeType` to `text/html`, `text/csv`, or `text/plain`.  When using HTML (the default) you should be able to move data between applications a little more seamlessly (if the other application supports html mime type).

A number of other features were required to implement this, like paste context menu etc..

I've added the lower right corner handle via `selectionHandleBehavior` attribute.  It is set to `none` by default and does nothing right now anyways.  I'll have it run duplication function on the selection once it's implemented, < 3 weeks.
