### ISSUE TITLE
How to Run Source Code, please

### ISSUE THREAD

**Issue by fikyair** [TonyGermaneri/canvas-datagrid#501]

**Comment by ndrsn** [comment]
Hi @fikyair , it depends on how you want to use canvas-datagrid: as web-component, using React, Vue, etc.

Have you seen the documentation at https://canvas-datagrid.js.org/ ? There are a bunch of examples under [Tutorials](https://canvas-datagrid.js.org/#tutorials), for example:

```js
var parentNode = document.getElementById('grid');

// Create a new grid
var grid = canvasDatagrid({
    parentNode: parentNode,
    data: [
        {col1: 'foo', col2: 0, col3: 'a'},
        {col1: 'bar', col2: 1, col3: 'b'},
        {col1: 'baz', col2: 2, col3: 'c'}
    ]
});
```

Does this help?
