### ISSUE TITLE
Clear Selection and Active Cell

### ISSUE THREAD

**Issue by luveti** [TonyGermaneri/canvas-datagrid#55]
I don't see any API methods that do this. But maybe I'm missing something. Is this currently possible?

**Comment by TonyGermaneri** [comment]
`grid.activeCell` is a property, sorry about the lack of an entry in the documentation.  There appears to be a few undocumented properties/methods, I tried to clean them all up in the last release after realizing they were undocumented.  You should find `grid.activeCell` there now.

`grid.selectArea` can be used to clear the selection (set everything to -1), but that seemed annoying so I added a new method: `grid.selectNone` which you'll find in 0.16.9.

**Comment by luveti** [comment]
Sweet thank you! :)
