### ISSUE TITLE
Is this project minimally active or it is better to find another one?

### ISSUE THREAD

**Issue by marionicolas** [TonyGermaneri/canvas-datagrid#579]
The project looks really good but as far as I start using it, im finding some basic things like gettin the filters applied or manipulated data, that seems to be impossible to workaround.
It looks like its been abandoned by the owner, but some PRs take course.

Does it worth it to use or contribute?

**Comment by ndrsn** [comment]
Hey Nico, yeah apologies — it's not been abandoned, I still have intentions to work on it and make some major improvements, but life and the real job have sucked up all available time. The original author himself unfortunately doesn't have much time either, but the issue board _is_ monitored.

I really hope to make some time available in August to get Typescript types implemented, and make some improvements to the codebase so we can do some internal refactoring. But honestly, no promises — there's quite a lot to do, and there's really no one else 'active' on this project but me

**Comment by marionicolas** [comment]
Thanxs for the reply! Its good to hear it is not abandoned, Im not the typescript kinda but ill take a look and see if can help
