### ISSUE TITLE
Move between cells using keyboard

### ISSUE THREAD

**Issue by anandanand84** [TonyGermaneri/canvas-datagrid#61]
Unable to move between cells using arrow keys after you edited some row in macos

Steps to reproduce.
1. Navigate to the demo.
2. Select a cell. Press Enter and edit something. Press enter again to complete edit.
3. Now move to next cell using arrow or tab.

Expected : 
Selection moves to adjacent cell.

Actual
Selection remains in the same cell

**Comment by TonyGermaneri** [comment]
Thanks for pointing this out.

**Comment by TonyGermaneri** [comment]
v0.18.3 fixes this problem.  Thanks again for pointing it out.
