### ISSUE TITLE
Copy pasting values after column re-order has wrong values in clipboard

### ISSUE THREAD

**Issue by stevewillard** [TonyGermaneri/canvas-datagrid#66]
If you swap two columns in the demo, for example, select cells from one column, and then copy and paste them into the other, the values are wrong. It looks like the copied values are based off the original column position.

**Comment by TonyGermaneri** [comment]
Thanks for finding the bug, I'll get it patched up soon.

**Comment by TonyGermaneri** [comment]
This still does not work.  I think it was only made worse.  I'll work on this next.  Sorry for the delay.
