### ISSUE TITLE
Great job! Hope support for pagination and thumbnails!

### ISSUE THREAD

**Issue by weijer** [TonyGermaneri/canvas-datagrid#7]
Great job! Hope support for pagination and thumbnails!

**Comment by TonyGermaneri** [comment]
Thanks for the vote of confidence!

Sorry the documentation is lacking.

Here's an example of how to draw thumbs onto the grid:

https://github.com/TonyGermaneri/canvas-datagrid#extending-behavior-by-drawing-on-the-canvas

If you think this method is too clunky and an interface for images should be added I'm open to adding that prior to V1.

As far as pagination, I'm not sure what you mean.  Would you like to see an interface to page data into the grid for paging data via XHR requests or are you suggesting displaying to the user a limited number of rows with the option to go to the previous/next page?

If you would like to see the former (page XHR data) right now I think it can be done.  One idea would be to pass in an empty dataset with the full length (e.g.: `var i = []; i[9999] = {};`) then attach to the scroll event and check what the top visible index is and request/draw data from there.  A debounce function is probably required as scroll fires quite a lot.  grid.data is a setter that calls draw eventually, so setting the data would update the visibility of the grid.

I'm open to adding a better interface for doing this before V1 with something less manual.

As for the later, as a user, I much prefer a pure scrollbar.  You can put any number of rows/columns into the grid without incurring the overhead required by standard HTML tables/methods, up to about 5 million rows.  If you have a use case for pagination I'd like to hear it.

**Comment by weijer** [comment]
5 million rows！wonderful！
