### ISSUE TITLE
[Question] Custom context menu

### ISSUE THREAD

**Issue by stevewillard** [TonyGermaneri/canvas-datagrid#70]
Hi there,

This is a really great library. I have a question, not an issue - is it possible to create a custom context menu? I would like to show my own options and HTML when the user right clicks on a column. Thanks!

Also, is this something you work on for fun, or is it part of your day job?

**Comment by betososa** [comment]
Hi, I find this https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#canvasDatagrid.contextMenuItem not sure if it is what you are looking for.

**Comment by stevewillard** [comment]
@betososa oh neat, thanks. I'll try specifying an HTML node for the title

**Comment by TonyGermaneri** [comment]
Just to add to what @betososa pointed out, there's a tutorial that shows an example.

https://tonygermaneri.github.io/canvas-datagrid/docs/index.html#tutorial--Create-complex-context-menu

> Also, is this something you work on for fun, or is it part of your day job?

It'll sound cliche, but writing this program is my purpose.  This is the 3rd attempt, and first serious public attempt at making this program.  The others, [like this one](https://github.com/TonyGermaneri/Rendition/blob/master/Rendition.Core/js/admin/UI/grid.js) or [this one](https://github.com/TonyGermaneri/Nina/wiki), where never made avaliable to the public in any meaninful way, but are really just prototypes for this program, hence they all share the same name "grid".

As a senior architect at Fandango.com I use and contribute to this open source project as well.  I find the grid incredibly useful and employ it in architecture whenever tabular or hierarchical data are displayed or manipulated, saving Fandango hundreds of engineering hours.

That being said, I started work on the grid long before I was employed by Fandango/NBC/Universial/Comcast, the grid is my own IP and it will always remain free open source software.  So please use it in your closed source projects, copy, manipulate and have no fear that any future license change will prevent you from employing it in the future.
