### ISSUE TITLE
[docs] Documentation crash in Chrome

### ISSUE THREAD

**Issue by anovsiradj** [TonyGermaneri/canvas-datagrid#80]
### Steps to reproduce the problem.
- open chrome
- visit <https://tonygermaneri.github.io/canvas-datagrid/docs/>
- after site loaded, suddenly crash

#### workaround
reload, clear cache, incognito, disabled extensions, (update) restart chrome.
but still not working.

### Specifications like the version of the project, operating system, or hardware.
Chrome:
version `63.0.3239.108 (Official Build) (64-bit)`
useragent `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.108 Safari/537.36`

Documentation:
version: `?`

---
thanks *(sory for my english)*.

**Comment by TonyGermaneri** [comment]
I'm unable to reproduce the issue.  The documentation site works by running [a function](https://tonygermaneri.github.io/canvas-datagrid/docs/js/main.js) against [an object declared in the global scope](https://tonygermaneri.github.io/canvas-datagrid/docs/js/reflection.js).  If it's crashing it's most likely producing an error in the console, or are you saying the browser terminates?

I'm using chrome 63.0.3239.84 on OSX.  I'll try it in windows after work tonight, but I'm pretty sure it works.

Can you check if there are any errors in the console?  It is a very resource intensive page, maybe you've run out of ram (not likely).

Your english is excellent.

**Comment by CorbinDallas** [comment]
I've tried it on Version 63.0.3239.108 (Official Build) (64-bit) at home and it appears to work without crashing.

**Comment by anovsiradj** [comment]
screencast:
https://youtu.be/6xKFmZ830Ug

i'am using ubuntu 16.04

**Comment by CorbinDallas** [comment]
Well, that's quite an error!  I can only assume that's happening to other users as well.  Maybe "everything on a single page" wasn't such a great design.  I'm glad you found a workaround.  In the next major version of the doc program I'll limit the size of the pages so this is less likely to happen.

**Comment by anovsiradj** [comment]
notes. after some experiment, i buld doc my self with disable this line: https://github.com/TonyGermaneri/canvas-datagrid/blob/d24ba821093a585e7df161858e4ac37e20adf314/tutorials/js/main.js#L311
no crash happened.

i think, there is something wrong wth ace-editor.

**Comment by CorbinDallas** [comment]
ah!  That's really helpful.  I can defer loading the ace editors in the tutorial until they are on-screen.  That should at least allow you to see the documentation portion even if looking at the tutorials will crash your browser.

Not sure why ace is crashing your browser though.  I use it as a code editor in the tutorials, I don't really want to get rid of it if I can help it.
