### ISSUE TITLE
Once grid.schema is set, there is no way to delete it

### ISSUE THREAD

**Issue by meixuexiang** [TonyGermaneri/canvas-datagrid#89]
When I use a grid instance to display multiple worksheets in Excel, there are some that I need to manipulate to set up the schema, and then I want to restore the schema to an unset state, but now I do not To, it is recommended to add such a feature, easy to use the same grid instance to display different formats of data

**Comment by TonyGermaneri** [comment]
The schema can be set again after it has been set.  There's no "unset" state.  When the grid is instantiated intialially the schema is set to `[{name: ''}];`.  So when you set the schema the first time you're really replacing the default one.  To set it back to the default state just call `grid.schema = [{name: ''}];`  If your data is not the same shape as the schema it will hide the data not represented in the schema.  Really, it just won't be aware of the data not defined in the schema.

The job of the schema array is to describe to the draw function what to look for in the data array's member objects.

I hope that answers your question.

**Comment by meixuexiang** [comment]
Thanks for your reply, however, unfortunately, setting grid.schema = [{name: ''}]; does not fulfill my needs because
`
  if (!self.schema) {
      self.tempSchema = self.getSchemaFromData();
  }
`

!self.schema is always equal to false, the program loses the ability to automatically generate a schema. If I want to represent different shapes of data, I have to destroy the current instance and then re-instantiate one.

**Comment by TonyGermaneri** [comment]
Oh! I see what you're saying.  I totally misunderstood what you were asking for.  I never considered the use case.  I'll add the functionality you need.  I'll modify the schema setter so if you pass in a falsey value it will erase all internal schema tracking (`self.tempSchema` and `self.schema`) setting it back to an uninitialized state which should cause the code path you referenced to execute (I believe that's in the data setter IIRC).  And to save you a little more time and make your code cleaner I'll add an attribute called `autoGenerateSchema`.  It will cause the data setter to always run `getSchemaFromData`.

`if (!self.schema || self.autoGenerateSchema) { self.tempSchema = self.getSchemaFromData(); }`

You should still be able to mutate the array after the data is set without having the setter called.

I'll try and take care of this before 1/22.  

## New behaviors

setting:
`grid.schema = undefined;`
will cause schema state initialization allowing for the data setter to auto-generate a schema from the data.

setting attribute `autoGenerateSchema` will cause the schema to always be auto-generated when data is set.

**Comment by TonyGermaneri** [comment]
Let me know how it works.  Open the ticket back up if you find it not to your liking or can think of a better way to do it.

**Comment by meixuexiang** [comment]
works well
