### ISSUE TITLE
How to use with angularjs?

### ISSUE THREAD

**Issue by SathishRaju** [TonyGermaneri/canvas-datagrid#91]
### Expected behavior and actual behavior.
Provide a sample to use with angular

### Steps to reproduce the problem.
Tried importing the JS file and then wrote a component based on it. But could not get it to work.

### Specifications like the version of the project, operating system, or hardware.

Angular 2.4.3

**Comment by meixuexiang** [comment]
`import { Component, OnInit, ViewContainerRef, Input, OnChanges, SimpleChanges } from '@angular/core';
import { CanvasDatagridOptions, Schema } from '../index.d';
import * as canvasDatagrid from 'canvas-datagrid';

@Component({
  selector: 'app-canvas-datagrid',
  templateUrl: './canvas-datagrid.component.html',
  styleUrls: ['./canvas-datagrid.component.css']
})
export class CanvasDatagridComponent implements OnInit, OnChanges {
  @Input() schema: Schema;
  @Input() data: any;
  @Input() datagridOpts: CanvasDatagridOptions;
  grid: any;
  constructor(private rootElement: ViewContainerRef) { }

  ngOnInit() { }

  ngOnChanges(changes: SimpleChanges) {
    console.log(changes);
    if (!this.grid && changes.hasOwnProperty('datagridOpts')) {
      const options = {
        ...this.datagridOpts,
        parentNode: this.rootElement.element.nativeElement
      };
      this.grid = canvasDatagrid(options);
      // this.grid.style.height = '100%';
      // this.grid.style.width = '100%';
      this.grid.style = {
        width: '100%',
        height: '100%',
        // background: 'rgba(255,255,255,0.8)'
      };
    }

    if (changes.hasOwnProperty('data')) {
      if (changes.data.currentValue) {
        if (this.grid.data !== changes.data.currentValue) {
          if (changes.hasOwnProperty('schema')) {
            this.grid.schema = changes.schema.currentValue || [{ name: '' }];
          }
          this.grid.data = changes.data.currentValue;
        } else {
          this.grid.draw();
        }
      }
    }
  }

  scrollIntoView(col: number, row: number) {
    this.grid.scrollIntoView(col, row);
  }

  fitColumnToValues(colName: string) {
    this.grid.fitColumnToValues(colName);
  }
}
`
This is a component in progress, hope helpful

**Comment by TonyGermaneri** [comment]
Thanks for supplying an example @meixuexiang.  I've been too busy to create one myself.  Do you mind if use it within an example for the main readme.md?

**Comment by Navya-adft** [comment]
can you provide a working angular example for this..
when i test this,it is not works

**Comment by ndrsn** [comment]
Closing, as it seems to have been answered.
